// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/app/penilaian": {
    params: {};
  };
  "/kalender": {
    params: {};
  };
  "/app/courses": {
    params: {};
  };
  "/app/student": {
    params: {};
  };
  "/app/onboarding": {
    params: {};
  };
  "/app/pengaturan": {
    params: {};
  };
  "/app/coming/:slug": {
    params: {
      "slug": string;
    };
  };
  "/app/tugas": {
    params: {};
  };
  "/app/tugas/buat": {
    params: {};
  };
  "/app/tugas/insights": {
    params: {};
  };
  "/app/riset": {
    params: {};
  };
  "/app/asisten": {
    params: {};
  };
  "/app/berkas": {
    params: {};
  };
  "/app/berkas/:fileId": {
    params: {
      "fileId": string;
    };
  };
  "/app/tugas/:assignmentId": {
    params: {
      "assignmentId": string;
    };
  };
  "/app/tugas/:assignmentId/pratinjau": {
    params: {
      "assignmentId": string;
    };
  };
  "/app/kerja/:assignmentId": {
    params: {
      "assignmentId": string;
    };
  };
  "/app/courses/:courseId": {
    params: {
      "courseId": string;
    };
  };
  "/app/courses/:courseId/:section": {
    params: {
      "courseId": string;
      "section": string;
    };
  };
  "/app/rps/:courseId": {
    params: {
      "courseId": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/api/rps-import": {
    params: {};
  };
  "/api/rps-assist": {
    params: {};
  };
  "/api/assignment-draft": {
    params: {};
  };
  "/api/task-config-draft": {
    params: {};
  };
  "/api/rubric-suggestions": {
    params: {};
  };
  "/api/course-thumbnail": {
    params: {};
  };
  "/api/task-submit": {
    params: {};
  };
  "/api/task-assist": {
    params: {};
  };
  "/api/feedback": {
    params: {};
  };
  "/api/evaluation-draft": {
    params: {};
  };
  "/api/evaluation-participants": {
    params: {};
  };
  "/api/evaluation-review": {
    params: {};
  };
  "/api/evaluation-annotation": {
    params: {};
  };
  "/api/evaluation-missed-error": {
    params: {};
  };
  "/api/evaluation-publish": {
    params: {};
  };
  "/api/research-export": {
    params: {};
  };
  "/api/research-analytics": {
    params: {};
  };
  "/api/personalization-analytics": {
    params: {};
  };
  "/api/feedback-uptake": {
    params: {};
  };
  "/api/evaluation-result": {
    params: {};
  };
  "/api/bulk-paper-prepare": {
    params: {};
  };
  "/api/bulk-paper-extract": {
    params: {};
  };
  "/api/bulk-paper-submit": {
    params: {};
  };
  "/api/transcribe": {
    params: {};
  };
  "/api/check-answer": {
    params: {};
  };
  "/api/roster-enroll": {
    params: {};
  };
  "/api/roster-status": {
    params: {};
  };
  "/api/roster-reset-password": {
    params: {};
  };
  "/api/roster-language": {
    params: {};
  };
  "/api/student-password": {
    params: {};
  };
  "/api/recovery-email/request": {
    params: {};
  };
  "/api/recovery-email/verify": {
    params: {};
  };
  "/api/recovery-email/request-reset": {
    params: {};
  };
  "/api/recovery-email/reset-password": {
    params: {};
  };
  "/api/practice-assist": {
    params: {};
  };
  "/api/practice-speaking": {
    params: {};
  };
  "/api/berkas-parse": {
    params: {};
  };
  "/api/berkas-process": {
    params: {};
  };
  "/api/berkas-suggest": {
    params: {};
  };
  "/api/berkas-snapshot": {
    params: {};
  };
  "/api/berkas-restore": {
    params: {};
  };
  "/api/context/check": {
    params: {};
  };
  "/api/context/insights": {
    params: {};
  };
  "/api/context/material": {
    params: {};
  };
  "/api/recommendations/generate": {
    params: {};
  };
  "/api/recommendations/review": {
    params: {};
  };
  "/verifikasi-email": {
    params: {};
  };
  "/lupa-sandi": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/tugas/:token": {
    params: {
      "token": string;
    };
  };
  "/api/integrated-ai/stream": {
    params: {};
  };
  "/api/ai-usage": {
    params: {};
  };
  "/api/assistant": {
    params: {};
  };
  "/api/student-assistant": {
    params: {};
  };
  "/api/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/app" | "/analytics" | "/app/penilaian" | "/kalender" | "/app/courses" | "/app/student" | "/app/onboarding" | "/app/pengaturan" | "/app/coming/:slug" | "/app/tugas" | "/app/tugas/buat" | "/app/tugas/insights" | "/app/riset" | "/app/asisten" | "/app/berkas" | "/app/berkas/:fileId" | "/app/tugas/:assignmentId" | "/app/tugas/:assignmentId/pratinjau" | "/app/kerja/:assignmentId" | "/app/courses/:courseId" | "/app/courses/:courseId/:section" | "/app/rps/:courseId" | "/sitemap.xml" | "/robots.txt" | "/api/health" | "/api/rps-import" | "/api/rps-assist" | "/api/assignment-draft" | "/api/task-config-draft" | "/api/rubric-suggestions" | "/api/course-thumbnail" | "/api/task-submit" | "/api/task-assist" | "/api/feedback" | "/api/evaluation-draft" | "/api/evaluation-participants" | "/api/evaluation-review" | "/api/evaluation-annotation" | "/api/evaluation-missed-error" | "/api/evaluation-publish" | "/api/research-export" | "/api/research-analytics" | "/api/personalization-analytics" | "/api/feedback-uptake" | "/api/evaluation-result" | "/api/bulk-paper-prepare" | "/api/bulk-paper-extract" | "/api/bulk-paper-submit" | "/api/transcribe" | "/api/check-answer" | "/api/roster-enroll" | "/api/roster-status" | "/api/roster-reset-password" | "/api/roster-language" | "/api/student-password" | "/api/recovery-email/request" | "/api/recovery-email/verify" | "/api/recovery-email/request-reset" | "/api/recovery-email/reset-password" | "/api/practice-assist" | "/api/practice-speaking" | "/api/berkas-parse" | "/api/berkas-process" | "/api/berkas-suggest" | "/api/berkas-snapshot" | "/api/berkas-restore" | "/api/context/check" | "/api/context/insights" | "/api/context/material" | "/api/recommendations/generate" | "/api/recommendations/review" | "/verifikasi-email" | "/lupa-sandi" | "/reset-password" | "/tugas/:token" | "/api/integrated-ai/stream" | "/api/ai-usage" | "/api/assistant" | "/api/student-assistant" | "/api/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app";
  };
  "routes/analytics.tsx": {
    id: "routes/analytics";
    page: "/analytics";
  };
  "routes/app.penilaian.tsx": {
    id: "routes/app.penilaian";
    page: "/app/penilaian";
  };
  "routes/kalender.tsx": {
    id: "routes/kalender";
    page: "/kalender";
  };
  "routes/app.courses.tsx": {
    id: "routes/app.courses";
    page: "/app/courses";
  };
  "routes/app.student.tsx": {
    id: "routes/app.student";
    page: "/app/student";
  };
  "routes/app.onboarding.tsx": {
    id: "routes/app.onboarding";
    page: "/app/onboarding";
  };
  "routes/app.pengaturan.tsx": {
    id: "routes/app.pengaturan";
    page: "/app/pengaturan";
  };
  "routes/app.coming.$slug.tsx": {
    id: "routes/app.coming.$slug";
    page: "/app/coming/:slug";
  };
  "routes/app.tugas.tsx": {
    id: "routes/app.tugas";
    page: "/app/tugas";
  };
  "routes/app.tugas.buat.tsx": {
    id: "routes/app.tugas.buat";
    page: "/app/tugas/buat";
  };
  "routes/app.tugas.insights.tsx": {
    id: "routes/app.tugas.insights";
    page: "/app/tugas/insights";
  };
  "routes/app.riset.tsx": {
    id: "routes/app.riset";
    page: "/app/riset";
  };
  "routes/app.asisten.tsx": {
    id: "routes/app.asisten";
    page: "/app/asisten";
  };
  "routes/app.berkas.tsx": {
    id: "routes/app.berkas";
    page: "/app/berkas";
  };
  "routes/app.berkas.$fileId.tsx": {
    id: "routes/app.berkas.$fileId";
    page: "/app/berkas/:fileId";
  };
  "routes/app.tugas.$assignmentId.tsx": {
    id: "routes/app.tugas.$assignmentId";
    page: "/app/tugas/:assignmentId";
  };
  "routes/app.tugas.$assignmentId.pratinjau.tsx": {
    id: "routes/app.tugas.$assignmentId.pratinjau";
    page: "/app/tugas/:assignmentId/pratinjau";
  };
  "routes/app.kerja.$assignmentId.tsx": {
    id: "routes/app.kerja.$assignmentId";
    page: "/app/kerja/:assignmentId";
  };
  "routes/course.tsx": {
    id: "routes/course";
    page: "/app/courses/:courseId" | "/app/courses/:courseId/:section";
  };
  "routes/course.index.tsx": {
    id: "routes/course.index";
    page: "/app/courses/:courseId";
  };
  "routes/course.section.tsx": {
    id: "routes/course.section";
    page: "/app/courses/:courseId/:section";
  };
  "routes/app.rps.$courseId.tsx": {
    id: "routes/app.rps.$courseId";
    page: "/app/rps/:courseId";
  };
  "routes/sitemap.xml.ts": {
    id: "routes/sitemap.xml";
    page: "/sitemap.xml";
  };
  "routes/robots.txt.ts": {
    id: "routes/robots.txt";
    page: "/robots.txt";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.rps-import.ts": {
    id: "routes/api.rps-import";
    page: "/api/rps-import";
  };
  "routes/api.rps-assist.ts": {
    id: "routes/api.rps-assist";
    page: "/api/rps-assist";
  };
  "routes/api.assignment-draft.ts": {
    id: "routes/api.assignment-draft";
    page: "/api/assignment-draft";
  };
  "routes/api.task-config-draft.ts": {
    id: "routes/api.task-config-draft";
    page: "/api/task-config-draft";
  };
  "routes/api.rubric-suggestions.ts": {
    id: "routes/api.rubric-suggestions";
    page: "/api/rubric-suggestions";
  };
  "routes/api.course-thumbnail.ts": {
    id: "routes/api.course-thumbnail";
    page: "/api/course-thumbnail";
  };
  "routes/api.task-submit.ts": {
    id: "routes/api.task-submit";
    page: "/api/task-submit";
  };
  "routes/api.task-assist.ts": {
    id: "routes/api.task-assist";
    page: "/api/task-assist";
  };
  "routes/api.feedback.ts": {
    id: "routes/api.feedback";
    page: "/api/feedback";
  };
  "routes/api.evaluation-draft.ts": {
    id: "routes/api.evaluation-draft";
    page: "/api/evaluation-draft";
  };
  "routes/api.evaluation-participants.ts": {
    id: "routes/api.evaluation-participants";
    page: "/api/evaluation-participants";
  };
  "routes/api.evaluation-review.ts": {
    id: "routes/api.evaluation-review";
    page: "/api/evaluation-review";
  };
  "routes/api.evaluation-annotation.ts": {
    id: "routes/api.evaluation-annotation";
    page: "/api/evaluation-annotation";
  };
  "routes/api.evaluation-missed-error.ts": {
    id: "routes/api.evaluation-missed-error";
    page: "/api/evaluation-missed-error";
  };
  "routes/api.evaluation-publish.ts": {
    id: "routes/api.evaluation-publish";
    page: "/api/evaluation-publish";
  };
  "routes/api.research-export.ts": {
    id: "routes/api.research-export";
    page: "/api/research-export";
  };
  "routes/api.research-analytics.ts": {
    id: "routes/api.research-analytics";
    page: "/api/research-analytics";
  };
  "routes/api.personalization-analytics.ts": {
    id: "routes/api.personalization-analytics";
    page: "/api/personalization-analytics";
  };
  "routes/api.feedback-uptake.ts": {
    id: "routes/api.feedback-uptake";
    page: "/api/feedback-uptake";
  };
  "routes/api.evaluation-result.ts": {
    id: "routes/api.evaluation-result";
    page: "/api/evaluation-result";
  };
  "routes/api.bulk-paper-prepare.ts": {
    id: "routes/api.bulk-paper-prepare";
    page: "/api/bulk-paper-prepare";
  };
  "routes/api.bulk-paper-extract.ts": {
    id: "routes/api.bulk-paper-extract";
    page: "/api/bulk-paper-extract";
  };
  "routes/api.bulk-paper-submit.ts": {
    id: "routes/api.bulk-paper-submit";
    page: "/api/bulk-paper-submit";
  };
  "routes/api.transcribe.ts": {
    id: "routes/api.transcribe";
    page: "/api/transcribe";
  };
  "routes/api.check-answer.ts": {
    id: "routes/api.check-answer";
    page: "/api/check-answer";
  };
  "routes/api.roster-enroll.ts": {
    id: "routes/api.roster-enroll";
    page: "/api/roster-enroll";
  };
  "routes/api.roster-status.ts": {
    id: "routes/api.roster-status";
    page: "/api/roster-status";
  };
  "routes/api.roster-reset-password.ts": {
    id: "routes/api.roster-reset-password";
    page: "/api/roster-reset-password";
  };
  "routes/api.roster-language.ts": {
    id: "routes/api.roster-language";
    page: "/api/roster-language";
  };
  "routes/api.student-password.ts": {
    id: "routes/api.student-password";
    page: "/api/student-password";
  };
  "routes/api.recovery-email-request.ts": {
    id: "routes/api.recovery-email-request";
    page: "/api/recovery-email/request";
  };
  "routes/api.recovery-email-verify.ts": {
    id: "routes/api.recovery-email-verify";
    page: "/api/recovery-email/verify";
  };
  "routes/api.recovery-email-request-reset.ts": {
    id: "routes/api.recovery-email-request-reset";
    page: "/api/recovery-email/request-reset";
  };
  "routes/api.recovery-email-reset-password.ts": {
    id: "routes/api.recovery-email-reset-password";
    page: "/api/recovery-email/reset-password";
  };
  "routes/api.practice-assist.ts": {
    id: "routes/api.practice-assist";
    page: "/api/practice-assist";
  };
  "routes/api.practice-speaking.ts": {
    id: "routes/api.practice-speaking";
    page: "/api/practice-speaking";
  };
  "routes/api.berkas-parse.ts": {
    id: "routes/api.berkas-parse";
    page: "/api/berkas-parse";
  };
  "routes/api.berkas-process.ts": {
    id: "routes/api.berkas-process";
    page: "/api/berkas-process";
  };
  "routes/api.berkas-suggest.ts": {
    id: "routes/api.berkas-suggest";
    page: "/api/berkas-suggest";
  };
  "routes/api.berkas-snapshot.ts": {
    id: "routes/api.berkas-snapshot";
    page: "/api/berkas-snapshot";
  };
  "routes/api.berkas-restore.ts": {
    id: "routes/api.berkas-restore";
    page: "/api/berkas-restore";
  };
  "routes/api.context-check.ts": {
    id: "routes/api.context-check";
    page: "/api/context/check";
  };
  "routes/api.context-insights.ts": {
    id: "routes/api.context-insights";
    page: "/api/context/insights";
  };
  "routes/api.context-material.ts": {
    id: "routes/api.context-material";
    page: "/api/context/material";
  };
  "routes/api.recommendations-generate.ts": {
    id: "routes/api.recommendations-generate";
    page: "/api/recommendations/generate";
  };
  "routes/api.recommendations-review.ts": {
    id: "routes/api.recommendations-review";
    page: "/api/recommendations/review";
  };
  "routes/verifikasi-email.tsx": {
    id: "routes/verifikasi-email";
    page: "/verifikasi-email";
  };
  "routes/lupa-sandi.tsx": {
    id: "routes/lupa-sandi";
    page: "/lupa-sandi";
  };
  "routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/tugas.$token.tsx": {
    id: "routes/tugas.$token";
    page: "/tugas/:token";
  };
  "routes/api.integrated-ai.stream.ts": {
    id: "routes/api.integrated-ai.stream";
    page: "/api/integrated-ai/stream";
  };
  "routes/api.ai-usage.ts": {
    id: "routes/api.ai-usage";
    page: "/api/ai-usage";
  };
  "routes/api.assistant.ts": {
    id: "routes/api.assistant";
    page: "/api/assistant";
  };
  "routes/api.student-assistant.ts": {
    id: "routes/api.student-assistant";
    page: "/api/student-assistant";
  };
  "routes/api.$.ts": {
    id: "routes/api.$";
    page: "/api/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/login": typeof import("./src/routes/login.tsx");
  "routes/app": typeof import("./src/routes/app.tsx");
  "routes/analytics": typeof import("./src/routes/analytics.tsx");
  "routes/app.penilaian": typeof import("./src/routes/app.penilaian.tsx");
  "routes/kalender": typeof import("./src/routes/kalender.tsx");
  "routes/app.courses": typeof import("./src/routes/app.courses.tsx");
  "routes/app.student": typeof import("./src/routes/app.student.tsx");
  "routes/app.onboarding": typeof import("./src/routes/app.onboarding.tsx");
  "routes/app.pengaturan": typeof import("./src/routes/app.pengaturan.tsx");
  "routes/app.coming.$slug": typeof import("./src/routes/app.coming.$slug.tsx");
  "routes/app.tugas": typeof import("./src/routes/app.tugas.tsx");
  "routes/app.tugas.buat": typeof import("./src/routes/app.tugas.buat.tsx");
  "routes/app.tugas.insights": typeof import("./src/routes/app.tugas.insights.tsx");
  "routes/app.riset": typeof import("./src/routes/app.riset.tsx");
  "routes/app.asisten": typeof import("./src/routes/app.asisten.tsx");
  "routes/app.berkas": typeof import("./src/routes/app.berkas.tsx");
  "routes/app.berkas.$fileId": typeof import("./src/routes/app.berkas.$fileId.tsx");
  "routes/app.tugas.$assignmentId": typeof import("./src/routes/app.tugas.$assignmentId.tsx");
  "routes/app.tugas.$assignmentId.pratinjau": typeof import("./src/routes/app.tugas.$assignmentId.pratinjau.tsx");
  "routes/app.kerja.$assignmentId": typeof import("./src/routes/app.kerja.$assignmentId.tsx");
  "routes/course": typeof import("./src/routes/course.tsx");
  "routes/course.index": typeof import("./src/routes/course.index.tsx");
  "routes/course.section": typeof import("./src/routes/course.section.tsx");
  "routes/app.rps.$courseId": typeof import("./src/routes/app.rps.$courseId.tsx");
  "routes/sitemap.xml": typeof import("./src/routes/sitemap.xml.ts");
  "routes/robots.txt": typeof import("./src/routes/robots.txt.ts");
  "routes/api.health": typeof import("./src/routes/api.health.ts");
  "routes/api.rps-import": typeof import("./src/routes/api.rps-import.ts");
  "routes/api.rps-assist": typeof import("./src/routes/api.rps-assist.ts");
  "routes/api.assignment-draft": typeof import("./src/routes/api.assignment-draft.ts");
  "routes/api.task-config-draft": typeof import("./src/routes/api.task-config-draft.ts");
  "routes/api.rubric-suggestions": typeof import("./src/routes/api.rubric-suggestions.ts");
  "routes/api.course-thumbnail": typeof import("./src/routes/api.course-thumbnail.ts");
  "routes/api.task-submit": typeof import("./src/routes/api.task-submit.ts");
  "routes/api.task-assist": typeof import("./src/routes/api.task-assist.ts");
  "routes/api.feedback": typeof import("./src/routes/api.feedback.ts");
  "routes/api.evaluation-draft": typeof import("./src/routes/api.evaluation-draft.ts");
  "routes/api.evaluation-participants": typeof import("./src/routes/api.evaluation-participants.ts");
  "routes/api.evaluation-review": typeof import("./src/routes/api.evaluation-review.ts");
  "routes/api.evaluation-annotation": typeof import("./src/routes/api.evaluation-annotation.ts");
  "routes/api.evaluation-missed-error": typeof import("./src/routes/api.evaluation-missed-error.ts");
  "routes/api.evaluation-publish": typeof import("./src/routes/api.evaluation-publish.ts");
  "routes/api.research-export": typeof import("./src/routes/api.research-export.ts");
  "routes/api.research-analytics": typeof import("./src/routes/api.research-analytics.ts");
  "routes/api.personalization-analytics": typeof import("./src/routes/api.personalization-analytics.ts");
  "routes/api.feedback-uptake": typeof import("./src/routes/api.feedback-uptake.ts");
  "routes/api.evaluation-result": typeof import("./src/routes/api.evaluation-result.ts");
  "routes/api.bulk-paper-prepare": typeof import("./src/routes/api.bulk-paper-prepare.ts");
  "routes/api.bulk-paper-extract": typeof import("./src/routes/api.bulk-paper-extract.ts");
  "routes/api.bulk-paper-submit": typeof import("./src/routes/api.bulk-paper-submit.ts");
  "routes/api.transcribe": typeof import("./src/routes/api.transcribe.ts");
  "routes/api.check-answer": typeof import("./src/routes/api.check-answer.ts");
  "routes/api.roster-enroll": typeof import("./src/routes/api.roster-enroll.ts");
  "routes/api.roster-status": typeof import("./src/routes/api.roster-status.ts");
  "routes/api.roster-reset-password": typeof import("./src/routes/api.roster-reset-password.ts");
  "routes/api.roster-language": typeof import("./src/routes/api.roster-language.ts");
  "routes/api.student-password": typeof import("./src/routes/api.student-password.ts");
  "routes/api.recovery-email-request": typeof import("./src/routes/api.recovery-email-request.ts");
  "routes/api.recovery-email-verify": typeof import("./src/routes/api.recovery-email-verify.ts");
  "routes/api.recovery-email-request-reset": typeof import("./src/routes/api.recovery-email-request-reset.ts");
  "routes/api.recovery-email-reset-password": typeof import("./src/routes/api.recovery-email-reset-password.ts");
  "routes/api.practice-assist": typeof import("./src/routes/api.practice-assist.ts");
  "routes/api.practice-speaking": typeof import("./src/routes/api.practice-speaking.ts");
  "routes/api.berkas-parse": typeof import("./src/routes/api.berkas-parse.ts");
  "routes/api.berkas-process": typeof import("./src/routes/api.berkas-process.ts");
  "routes/api.berkas-suggest": typeof import("./src/routes/api.berkas-suggest.ts");
  "routes/api.berkas-snapshot": typeof import("./src/routes/api.berkas-snapshot.ts");
  "routes/api.berkas-restore": typeof import("./src/routes/api.berkas-restore.ts");
  "routes/api.context-check": typeof import("./src/routes/api.context-check.ts");
  "routes/api.context-insights": typeof import("./src/routes/api.context-insights.ts");
  "routes/api.context-material": typeof import("./src/routes/api.context-material.ts");
  "routes/api.recommendations-generate": typeof import("./src/routes/api.recommendations-generate.ts");
  "routes/api.recommendations-review": typeof import("./src/routes/api.recommendations-review.ts");
  "routes/verifikasi-email": typeof import("./src/routes/verifikasi-email.tsx");
  "routes/lupa-sandi": typeof import("./src/routes/lupa-sandi.tsx");
  "routes/reset-password": typeof import("./src/routes/reset-password.tsx");
  "routes/tugas.$token": typeof import("./src/routes/tugas.$token.tsx");
  "routes/api.integrated-ai.stream": typeof import("./src/routes/api.integrated-ai.stream.ts");
  "routes/api.ai-usage": typeof import("./src/routes/api.ai-usage.ts");
  "routes/api.assistant": typeof import("./src/routes/api.assistant.ts");
  "routes/api.student-assistant": typeof import("./src/routes/api.student-assistant.ts");
  "routes/api.$": typeof import("./src/routes/api.$.ts");
};