import { type RouteConfig, index, route } from '@react-router/dev/routes';

export default [
	index('routes/home.tsx'),
	route('hcgi/platform/api/*', 'routes/hcgi.platform.$.ts'),
	route('login', 'routes/login.tsx'),
	route('app', 'routes/app.tsx'),
	route('analytics', 'routes/analytics.tsx'),
	route('app/penilaian', 'routes/app.penilaian.tsx'),
	route('kalender', 'routes/kalender.tsx'),
	route('app/courses', 'routes/app.courses.tsx'),
	route('app/student', 'routes/app.student.tsx'),
	route('app/latihan', 'routes/app.latihan.tsx'),
	route('app/onboarding', 'routes/app.onboarding.tsx'),
	route('app/pengaturan', 'routes/app.pengaturan.tsx'),
	route('app/coming/:slug', 'routes/app.coming.$slug.tsx'),
	route('app/tugas', 'routes/app.tugas.tsx'),
	route('app/tugas/buat', 'routes/app.tugas.buat.tsx'),
	route('app/tugas/insights', 'routes/app.tugas.insights.tsx'),
	route('app/riset', 'routes/app.riset.tsx'),
	route('app/asisten', 'routes/app.asisten.tsx'),
	route('app/berkas', 'routes/app.berkas.tsx'),
	route('app/berkas/:fileId', 'routes/app.berkas.$fileId.tsx'),
	route('app/tugas/:assignmentId', 'routes/app.tugas.$assignmentId.tsx'),
	route('app/tugas/:assignmentId/pratinjau', 'routes/app.tugas.$assignmentId.pratinjau.tsx'),
	route('app/kerja/:assignmentId', 'routes/app.kerja.$assignmentId.tsx'),
	route('app/courses/:courseId', 'routes/course.tsx', [
		index('routes/course.index.tsx'),
		route('pertemuan/:sessionId/rencana', 'routes/course.lesson-plan.tsx'),
		route('mahasiswa/:rosterId', 'routes/course.student-profile.tsx'),
		route(':section', 'routes/course.section.tsx'),
	]),
	route('app/rps/:courseId', 'routes/app.rps.$courseId.tsx'),
	route('sitemap.xml', 'routes/sitemap.xml.ts'),
	route('robots.txt', 'routes/robots.txt.ts'),
	route('api/health', 'routes/api.health.ts'),
	route('api/rps-import', 'routes/api.rps-import.ts'),
	route('api/rps-assist', 'routes/api.rps-assist.ts'),
	route('api/assignment-draft', 'routes/api.assignment-draft.ts'),
	route('api/task-config-draft', 'routes/api.task-config-draft.ts'),
	route('api/rubric-suggestions', 'routes/api.rubric-suggestions.ts'),
	route('api/course-thumbnail', 'routes/api.course-thumbnail.ts'),
	route('api/task-submit', 'routes/api.task-submit.ts'),
	route('api/task-assist', 'routes/api.task-assist.ts'),
	route('api/feedback', 'routes/api.feedback.ts'),
	route('api/evaluation-draft', 'routes/api.evaluation-draft.ts'),
	route('api/evaluation-participants', 'routes/api.evaluation-participants.ts'),
	route('api/evaluation-review', 'routes/api.evaluation-review.ts'),
	route('api/evaluation-annotation', 'routes/api.evaluation-annotation.ts'),
	route('api/evaluation-missed-error', 'routes/api.evaluation-missed-error.ts'),
	route('api/evaluation-publish', 'routes/api.evaluation-publish.ts'),
	route('api/research-export', 'routes/api.research-export.ts'),
	route('api/research-analytics', 'routes/api.research-analytics.ts'),
	route('api/personalization-analytics', 'routes/api.personalization-analytics.ts'),
	route('api/feedback-uptake', 'routes/api.feedback-uptake.ts'),
	route('api/evaluation-result', 'routes/api.evaluation-result.ts'),
	route('api/bulk-paper-prepare', 'routes/api.bulk-paper-prepare.ts'),
	route('api/bulk-paper-extract', 'routes/api.bulk-paper-extract.ts'),
	route('api/bulk-paper-submit', 'routes/api.bulk-paper-submit.ts'),
	route('api/transcribe', 'routes/api.transcribe.ts'),
	route('api/check-answer', 'routes/api.check-answer.ts'),
	route('api/roster-enroll', 'routes/api.roster-enroll.ts'),
	route('api/roster-status', 'routes/api.roster-status.ts'),
	route('api/roster-reset-password', 'routes/api.roster-reset-password.ts'),
	route('api/roster-language', 'routes/api.roster-language.ts'),
	route('api/student-password', 'routes/api.student-password.ts'),
	route('api/recovery-email/request', 'routes/api.recovery-email-request.ts'),
	route('api/recovery-email/verify', 'routes/api.recovery-email-verify.ts'),
	route('api/recovery-email/request-reset', 'routes/api.recovery-email-request-reset.ts'),
	route('api/recovery-email/reset-password', 'routes/api.recovery-email-reset-password.ts'),
	route('api/practice-assist', 'routes/api.practice-assist.ts'),
    route('api/conversation-practice', 'routes/api.conversation-practice.ts'),
	route('api/personal-practice', 'routes/api.personal-practice.ts'),
    route('api/course-grade-summary', 'routes/api.course-grade-summary.ts'),
	route('api/student-profile', 'routes/api.student-profile.ts'),
	route('api/practice-speaking', 'routes/api.practice-speaking.ts'),
	route('api/berkas-parse', 'routes/api.berkas-parse.ts'),
	route('api/berkas-process', 'routes/api.berkas-process.ts'),
	route('api/berkas-suggest', 'routes/api.berkas-suggest.ts'),
	route('api/berkas-snapshot', 'routes/api.berkas-snapshot.ts'),
	route('api/berkas-restore', 'routes/api.berkas-restore.ts'),
	route('api/context/check', 'routes/api.context-check.ts'),
	route('api/context/insights', 'routes/api.context-insights.ts'),
	route('api/context/material', 'routes/api.context-material.ts'),
	route('api/recommendations/generate', 'routes/api.recommendations-generate.ts'),
	route('api/recommendations/review', 'routes/api.recommendations-review.ts'),
	route('verifikasi-email', 'routes/verifikasi-email.tsx'),
	route('lupa-sandi', 'routes/lupa-sandi.tsx'),
	route('reset-password', 'routes/reset-password.tsx'),
	route('tugas/:token', 'routes/tugas.$token.tsx'),
	route('api/integrated-ai/stream', 'routes/api.integrated-ai.stream.ts'),
	route('api/ai-usage', 'routes/api.ai-usage.ts'),
	route('api/lesson-plans','routes/api.lesson-plans.ts'),
	route('api/agent-tasks', 'routes/api.agent-tasks.ts'),
	route('api/assistant', 'routes/api.assistant.ts'),
	route('api/student-assistant', 'routes/api.student-assistant.ts'),
	route('api/*', 'routes/api.$.ts'),
] satisfies RouteConfig;
