import { useEffect,useMemo,useState } from 'react';
import { Link,useParams,useSearchParams } from 'react-router';
import pb from '@/lib/pocketbase-client';
import { useCourseByRoute } from '@/hooks/use-course-route';
import type { ClassSession } from '@/lib/learning';
import type { LessonPlan } from '@/lib/agent-tasks';
import { emptyLessonPlan,type SessionLessonPlan } from '@/lib/lesson-plans';
import { AgentTaskPanel } from '@/components/app/agent-task-panel';
import { ArrowDown,ArrowUp,Copy,Plus,Save,Trash2 } from 'lucide-react';
type Revision={id:string;revision:number;origin:string;created:string;snapshot:{plan:LessonPlan;status:'draft'|'ready'}};
type Material={id:string;title:string;version:number};
type Outcome={id:string;code:string;description:string};
const post=async(body:Record<string,unknown>)=>{const r=await fetch('/api/lesson-plans',{method:'POST',headers:{Authorization:`Bearer ${pb.authStore.token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Rencana belum tersimpan.');return data.plan as SessionLessonPlan;};
export function meta(){return [{title:'Rencana pembelajaran | LARAS'}];}
export default function LessonPlanPage(){
 const {courseId='',sessionId=''}=useParams(),[params]=useSearchParams();const course=useCourseByRoute(courseId).data;
 const supplied=useMemo(()=>course?[course]:[],[course]);
 const [session,setSession]=useState<ClassSession|null>(null),[record,setRecord]=useState<SessionLessonPlan|null>(null),[form,setForm]=useState<LessonPlan|null>(null),[status,setStatus]=useState<'draft'|'ready'>('draft');
 const [materials,setMaterials]=useState<Material[]>([]),[outcomes,setOutcomes]=useState<Outcome[]>([]),[revisions,setRevisions]=useState<Revision[]>([]),[legacy,setLegacy]=useState<SessionLessonPlan[]>([]),[sourceId,setSourceId]=useState(params.get('attach')||'');
 const [dirty,setDirty]=useState(false),[remoteChanged,setRemoteChanged]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const accept=(p:SessionLessonPlan)=>{setRecord(p);setForm(p.plan||emptyLessonPlan(p.title));setStatus(p.status||'draft');setDirty(false);setRemoteChanged(false);};
 const history=async(id:string)=>setRevisions(await pb.collection('lesson_plan_revisions').getFullList<Revision>({filter:pb.filter('lessonPlan={:id}',{id}),sort:'-revision'}));
 useEffect(()=>{if(!course)return;let alive=true;setError('');setForm(null);
 void (async()=>{if(course.owner!==pb.authStore.record?.id)throw new Error('Rencana pembelajaran hanya untuk dosen pemilik.');const meeting=await pb.collection('class_sessions').getOne<ClassSession>(sessionId);if(meeting.course!==course.id)throw new Error('Pertemuan tidak sesuai mata kuliah.');const p=await post({action:'ensure',sessionId});if(!alive)return;setSession(meeting);accept(p);if(!p.plan)setForm({...emptyLessonPlan(p.title),objective:meeting.learningIndicator||'',outcomeIds:[...(meeting.cpmks||[]),...(meeting.subCpmks||[])]});await history(p.id);
 const filter=pb.filter('course={:c} && owner={:u}',{c:course.id,u:pb.authStore.record?.id});
 const [files,cpmks,subs,old]=await Promise.all([pb.collection('file_library').getFullList<Material>({filter}),pb.collection('cpmk').getFullList<Outcome>({filter}),pb.collection('sub_cpmk').getFullList<Outcome>({filter}),pb.collection('assistant_lesson_plans').getFullList<SessionLessonPlan>({filter:filter+' && session=""'})]);if(alive){setMaterials(files);setOutcomes([...cpmks,...subs]);setLegacy(old);}
 })().catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[course?.id,sessionId]);
 useEffect(()=>{if(!record)return;let alive=true;const timer=setInterval(()=>{void pb.collection('assistant_lesson_plans').getOne<SessionLessonPlan>(record.id).then(p=>{if(!alive||p.revision===record.revision)return;if(dirty)setRemoteChanged(true);else{accept(p);void history(p.id);}}).catch(()=>{});},5000);return()=>{alive=false;clearInterval(timer);};},[record?.id,record?.revision,dirty]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const change=(patch:Partial<LessonPlan>)=>{setForm(f=>f?{...f,...patch}:f);setDirty(true);setNotice('');};
 const activity=(index:number,patch:Partial<LessonPlan['activities'][number]>)=>change({activities:form!.activities.map((a,i)=>i===index?{...a,...patch}:a)});
 const move=(index:number,direction:number)=>{const rows=[...form!.activities];const j=index+direction;if(j<0||j>=rows.length)return;[rows[index],rows[j]]=[rows[j],rows[index]];change({activities:rows});};
 const save=async(action='save')=>{if(!record||!form||busy)return;setBusy(true);setError('');try{const p=await post({action,sessionId,baseRevision:record.revision,plan:form,status,sourceId});accept(p);await history(p.id);setLegacy(rows=>rows.filter(r=>r.id!==sourceId));setNotice('Rencana tersimpan dan diperiksa.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 if(error&&!form)return <div className="lp-page"><p role="alert">{error}</p><Link to={`/app/courses/${courseId}/mata-kuliah`}>Kembali ke pertemuan</Link></div>;
 if(!course||!session||!form||!record)return <div className="lp-page">Memuat rencana pembelajaran…</div>;
 const minutes=form.activities.reduce((sum,a)=>sum+(Number(a.minutes)||0),0),allocation=Number(session.duration?.match(/\d+/)?.[0])||0;
 return <div className="lp-page">
 <Link className="ld-text-btn" to={`/app/courses/${course.id}/mata-kuliah`}>← Pertemuan</Link>
 <header className="lp-head"><div><small>MINGGU {session.week} · {course.title}</small><h1>Rencana pembelajaran</h1><p>{session.title} {session.date&&`· ${new Date(session.date).toLocaleDateString('id-ID', { timeZone: 'Asia/Jakarta' })}`}</p></div><span className="lp-badge">{record.status==='ready'?'Siap':'Draf'} · revisi {record.revision||0}</span></header>
 <nav className="lp-tabs"><Link to={`/app/courses/${course.id}/mata-kuliah`}>Pertemuan</Link><span aria-current="page">Rencana pembelajaran</span></nav>
 <p className="lp-private">Pribadi untuk dosen. Status Siap tidak mempublikasikan rencana kepada mahasiswa.</p>
 {error&&<p className="lp-alert" role="alert">{error}</p>}{notice&&<p role="status" className="lp-success">{notice}</p>}
 {remoteChanged&&<div className="lp-alert">Ada revisi baru. Salin perubahan Anda sebelum memuat versi terbaru.<button onClick={()=>void post({action:'ensure',sessionId}).then(accept)}>Muat versi terbaru</button></div>}
 <div className="lp-layout"><fieldset className="lp-editor" disabled={busy}>
 {legacy.length>0&&record.revision===0&&<section className="lp-card"><h2>Tautkan draf yang sudah ada</h2><select aria-label="Draf terpisah" value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Pilih draf…</option>{legacy.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><button className="ld-btn-outline" disabled={!sourceId||busy||dirty} onClick={()=>void save('attach')}>Tautkan ke pertemuan ini</button></section>}
 <section className="lp-card"><h2>Tujuan dan persiapan</h2><label>Judul<input value={form.title} onChange={e=>change({title:e.target.value})} maxLength={200}/></label><label>Tujuan pembelajaran<textarea value={form.objective} onChange={e=>change({objective:e.target.value})}/></label><fieldset><legend>CPMK / Sub-CPMK</legend>{!outcomes.length&&<p>Belum ada capaian terstruktur pada mata kuliah ini.</p>}{outcomes.map(o=><label className="lp-check" key={o.id}><input type="checkbox" checked={form.outcomeIds?.includes(o.id)||false} onChange={e=>change({outcomeIds:e.target.checked?[...(form.outcomeIds||[]),o.id]:(form.outcomeIds||[]).filter(id=>id!==o.id)})}/><span>{o.code} · {o.description}</span></label>)}</fieldset><label>Persiapan dosen<textarea value={form.preparation||''} onChange={e=>change({preparation:e.target.value})} placeholder="Bahan, alat, atau catatan sebelum kelas"/></label></section>
 <section className="lp-card"><header className="lp-section-head"><h2>Rundown</h2><strong>{minutes} menit{allocation?` / ${allocation} menit`:''}</strong></header>{allocation>0&&minutes>allocation&&<p className="lp-alert">Rundown melebihi durasi pertemuan sebesar {minutes-allocation} menit.</p>}{form.activities.map((a,i)=><article className="lp-activity" key={i}><header><strong>Kegiatan {i+1}</strong><div><button aria-label={`Naikkan kegiatan ${i+1}`} disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={15}/></button><button aria-label={`Turunkan kegiatan ${i+1}`} disabled={i===form.activities.length-1} onClick={()=>move(i,1)}><ArrowDown size={15}/></button><button aria-label={`Duplikasi kegiatan ${i+1}`} onClick={()=>change({activities:form.activities.flatMap((row,j)=>j===i?[row,{...row,sourceIds:[...row.sourceIds]}]:[row])})}><Copy size={15}/></button><button aria-label={`Hapus kegiatan ${i+1}`} onClick={()=>change({activities:form.activities.filter((_,j)=>j!==i)})}><Trash2 size={15}/></button></div></header><div className="lp-pair"><label>Nama kegiatan<input value={a.title} onChange={e=>activity(i,{title:e.target.value})}/></label><label>Durasi (menit)<input type="number" min={1} max={600} value={a.minutes} onChange={e=>activity(i,{minutes:Number(e.target.value)})}/></label></div><label>Instruksi dosen<textarea value={a.instructions} onChange={e=>activity(i,{instructions:e.target.value})}/></label><label>Aktivitas mahasiswa<textarea value={a.studentActivity||''} onChange={e=>activity(i,{studentActivity:e.target.value})}/></label><details><summary>Materi kegiatan ({a.sourceIds.length})</summary>{materials.map(m=><label className="lp-check" key={m.id}><input type="checkbox" checked={a.sourceIds.includes(m.id)} onChange={e=>{const ids=e.target.checked?[...a.sourceIds,m.id]:a.sourceIds.filter(id=>id!==m.id);const sources=form.sources.some(s=>s.id===m.id)?form.sources:[...form.sources,{id:m.id,title:m.title,version:m.version||1,href:`/app/berkas/${m.id}`,locator:'',sectionIds:[]}];change({sources,activities:form.activities.map((row,j)=>j===i?{...row,sourceIds:ids}:row)});}}/><span>{m.title}</span><Link to={`/app/berkas/${m.id}`}>Buka PDF / materi ↗</Link></label>)}</details></article>)}<button className="ld-btn-outline" onClick={()=>change({activities:[...form.activities,{title:'',minutes:10,instructions:'',studentActivity:'',sourceIds:[]}]})}><Plus size={15}/>Tambah kegiatan</button></section>
 <section className="lp-card"><h2>Cek pemahaman</h2><label>Metode / pertanyaan<textarea value={form.check} onChange={e=>change({check:e.target.value})}/></label>{form.evidenceNote&&<p className="lp-private">{form.evidenceNote}</p>}</section>
 <div className="lp-save"><label>Status<select value={status} onChange={e=>{setStatus(e.target.value as 'draft'|'ready');setDirty(true);}}><option value="draft">Draf</option><option value="ready">Siap</option></select></label><button className="ld-btn-primary" disabled={busy||remoteChanged} onClick={()=>void save()}><Save size={16}/>{busy?'Menyimpan…':'Simpan rencana'}</button><small>{dirty?'Perubahan belum tersimpan':`Revisi ${record.revision||0} tersimpan`}</small></div>
 </fieldset><aside className="lp-side"><AgentTaskPanel courses={supplied} sessionId={sessionId}/><section className="lp-card"><h2>Riwayat revisi</h2>{!revisions.length&&<p>Riwayat muncul setelah rencana disimpan.</p>}{revisions.map(r=><details key={r.id}><summary>Revisi {r.revision} · {r.origin==='ai'?'Usulan AI disetujui':r.origin==='attach'?'Draf ditautkan':'Edit dosen'} · {new Date(r.created).toLocaleString('id-ID')}</summary><p>{r.snapshot.plan.title}</p><p>{r.snapshot.plan.objective}</p><ol>{r.snapshot.plan.activities.map((a,i)=><li key={i}>{a.title} · {a.minutes} menit</li>)}</ol><button className="ld-text-btn" disabled={busy} onClick={()=>{setForm(r.snapshot.plan);setStatus('draft');setDirty(true);setNotice('Versi lama dimuat ke editor. Simpan untuk membuat revisi baru.');}}>Gunakan sebagai draf baru</button></details>)}</section></aside></div>
 </div>;
}
