import * as Dialog from '@radix-ui/react-dialog';
import {useEffect,useState} from 'react';
import pb from '@/lib/pocketbase-client';
import {useCachedQuery} from '@/hooks/use-cached-query';
import {useCourseRoster} from '@/hooks/use-course-roster';
import {useCourseSections} from '@/hooks/use-course-sections';
import {useSessionAttendance,type AttendanceStatus} from '@/hooks/use-attendance';
import {dateLabel,errorMessage,type ClassSession,type CourseRosterEntry} from '@/lib/learning';
import {invalidate} from '@/lib/local-cache';
import '@/styles/session-roster.css';
type Award={id:string;roster:string;student:string;session:string;points:number;reason:string;note:string;revoked:boolean;created:string};
const statuses=[['present','Hadir'],['late','Terlambat'],['excused','Izin'],['sick','Sakit'],['absent','Absen']] as const;
export function SessionRoster({courseId,canEdit,sectionId}:{courseId:string;canEdit:boolean;sectionId?:string}){
 const {entries,loading}=useCourseRoster(courseId),{sections}=useCourseSections(courseId);
 const sq=useCachedQuery<(ClassSession&{attendanceClosed:boolean})[]>(`class_sessions:course=${courseId}`,()=>pb.collection('class_sessions').getFullList({filter:pb.filter('course={:c}',{c:courseId}),sort:'date,week'}));
 const bonusQuery=useCachedQuery<{maxScore:number}[]>(`participation:bonus:${courseId}`,()=>pb.collection('grade_components').getFullList({filter:pb.filter('course={:c} && sourceType="bonus" && status="active"',{c:courseId})}));
 const cap=bonusQuery.data?.[0]?.maxScore ?? 5;
 const aq=useCachedQuery<Award[]>(`participation:${courseId}`,()=>pb.collection('participation_awards').getFullList({filter:pb.filter('session.course={:c}',{c:courseId}),sort:'-created'}));
 const [kelas,setKelas]=useState(sectionId||''),[selected,setSelected]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('Semua perubahan tersimpan');
 const [award,setAward]=useState<{entry:CourseRosterEntry;points:number}|null>(null),[reason,setReason]=useState('Menjawab'),[note,setNote]=useState('');
 const [undo,setUndo]=useState<(()=>Promise<void>)|null>(null);
 const sessions=(sq.data||[]).filter(s=>!kelas||!s.section||s.section===kelas);
 useEffect(()=>{if(!sessions.length||sessions.some(s=>s.id===selected))return;const requested=new URLSearchParams(window.location.search).get('session'),today=new Date(Date.now()+7*3600000).toISOString().slice(0,10);setSelected(sessions.find(s=>s.id===requested)?.id||[...sessions].reverse().find(s=>s.date&&s.date.slice(0,10)<=today)?.id||sessions[0].id);},[sq.data,kelas,selected]);
 useEffect(()=>setUndo(null),[selected]);
 const session=sessions.find(s=>s.id===selected),{map,loading:attLoading,error:attError,reload}=useSessionAttendance(selected);
 const roster=entries.filter(e=>session?.section?e.section===session.section:!kelas||e.section===kelas);
 const awards=(aq.data||[]).filter(a=>!a.revoked),current=awards.filter(a=>a.session===selected);
 const missing=roster.filter(e=>!map.has(e.id)).length,closed=Boolean(session?.attendanceClosed),disabled=!canEdit||busy||closed||attLoading||Boolean(aq.error);
 const visible=roster.filter(e=>(e.name+' '+e.nim).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||(filter==='missing'?!map.has(e.id):map.get(e.id)?.status===filter)));
 async function mutate(fn:()=>Promise<void>){setBusy(true);setError('');setSaved('Menyimpan…');try{await fn();invalidate('attendance');invalidate('gradebook');await Promise.all([reload(),aq.reload()]);setSaved('Semua perubahan tersimpan');}catch(e){setError(errorMessage(e));setSaved('Perubahan belum tersimpan');await reload();}finally{setBusy(false);}}
 async function write(entry:CourseRosterEntry,status:AttendanceStatus){const existing=map.get(entry.id);return existing?pb.collection('attendance').update(existing.id,{status}):pb.collection('attendance').create({session:selected,roster:entry.id,section:session?.section||entry.section||'',owner:pb.authStore.record?.id,status});}
 function mark(entry:CourseRosterEntry,status:AttendanceStatus){const old=map.get(entry.id);void mutate(async()=>{const rec=await write(entry,status);setUndo(()=>async()=>{if(old)await pb.collection('attendance').update(old.id,{status:old.status});else await pb.collection('attendance').delete(rec.id);});});}
 return <div className="session-roster"><header className="sr-heading"><div><span className="ld-eyebrow">SAAT PERTEMUAN</span><h2>Absensi & Keaktivan</h2><p>Catat kehadiran dan apresiasi partisipasi. Terhubung ke Penilaian.</p></div><span role="status">{busy?'Menyimpan…':saved}</span></header>
 <div className="sr-toolbar"><label>Kelas<select aria-label="Kelas" value={kelas} disabled={busy} onChange={e=>{setKelas(e.target.value);setSelected('');}}><option value="">Semua kelas</option>{sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Pertemuan<select aria-label="Pertemuan" value={selected} disabled={busy} onChange={e=>setSelected(e.target.value)}>{sessions.map(s=><option value={s.id} key={s.id}>Minggu {s.week} · {s.title} · {s.date?dateLabel(s.date):'Belum dijadwalkan'}</option>)}</select></label></div>
 {(error||attError||sq.error||aq.error)&&<div className="ld-alert" role="alert">{error||attError||String(sq.error||aq.error)}</div>}
 {loading||sq.loading?<p>Memuat mahasiswa…</p>:!session?<p>Tambahkan pertemuan terlebih dahulu.</p>:<><div className="sr-stats">{[['Hadir',roster.filter(e=>map.get(e.id)?.status==='present').length],['Terlambat',roster.filter(e=>map.get(e.id)?.status==='late').length],['Belum dicatat',missing],['Poin sesi',current.reduce((s,a)=>s+a.points,0)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 <div className="sr-toolbar"><input aria-label="Cari mahasiswa" placeholder="Cari nama atau NIM…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter kehadiran" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Semua mahasiswa</option><option value="missing">Belum dicatat</option>{statuses.map(([s,l])=><option key={s} value={s}>{l}</option>)}</select><button disabled={disabled||!missing} onClick={()=>void mutate(async()=>{for(const e of roster.filter(e=>!map.has(e.id)))await write(e,'present');setUndo(null);})}>Tandai yang belum dicatat hadir</button></div>
 <div className="sr-list"><div className="sr-row sr-labels"><span>Mahasiswa · {roster.length}</span><span>Kehadiran</span><span>Keaktivan sesi</span></div>{visible.map(entry=><div className="sr-row" key={entry.id}><div><strong>{entry.name}</strong><small>{entry.nim}</small></div><div className="sr-status">{statuses.map(([s,l])=><button key={s} aria-label={`${l} — ${entry.name}`} aria-pressed={map.get(entry.id)?.status===s} className={map.get(entry.id)?.status===s?'selected':''} disabled={disabled} onClick={()=>mark(entry,s)}>{l}</button>)}</div><div className="sr-points"><span>+{current.filter(a=>a.roster===entry.id).reduce((s,a)=>s+a.points,0)}</span>{[0.5,1].map(points=><button key={points} disabled={disabled} aria-label={`Tambah ${points} poin untuk ${entry.name}`} onClick={()=>{setAward({entry,points});setReason('Menjawab');setNote('');}}>+{points}</button>)}<small>Bonus kursus +{Math.min(cap,awards.filter(a=>a.roster===entry.id).reduce((s,a)=>s+a.points,0))} / {cap} maks.</small></div></div>)}{!visible.length&&<p>Tidak ada mahasiswa sesuai filter. Tambahkan mahasiswa melalui tab Mahasiswa.</p>}</div>
 <details className="sr-history"><summary>Riwayat keaktivan sesi · {current.length} apresiasi</summary>{(aq.data||[]).filter(a=>a.session===selected).map(a=><div key={a.id}><span><strong>{entries.find(e=>e.id===a.roster)?.name}</strong> · +{a.points} · {a.reason}{a.note?' · '+a.note:''}<small>{new Date(a.created).toLocaleString('id-ID')}{a.revoked?' · Dibatalkan':''}</small></span>{!a.revoked&&<button disabled={disabled} onClick={()=>void mutate(async()=>{await pb.collection('participation_awards').update(a.id,{revoked:true});})}>Batalkan poin</button>}</div>)}</details>
 <footer className="sr-footer"><div><strong>{roster.length-missing}/{roster.length} kehadiran tercatat</strong><small>{closed?'Pencatatan selesai. Buka kembali untuk koreksi.':missing?'Lengkapi mahasiswa yang belum dicatat.':'Siap menyelesaikan pencatatan.'}</small></div>{undo&&!closed&&<button disabled={busy} onClick={()=>void mutate(async()=>{await undo();setUndo(null);})}>Urungkan terakhir</button>}<button className="sr-primary" disabled={!canEdit||busy||attLoading||(!closed&&(missing>0||!roster.length))} onClick={()=>void mutate(async()=>{await pb.collection('class_sessions').update(selected,{attendanceClosed:!closed});await sq.reload();})}>{closed?'Buka kembali':'Selesaikan pencatatan'}</button></footer></>}
 {award&&<Dialog.Root open onOpenChange={open=>{if(!open&&!busy)setAward(null);}}><Dialog.Portal><Dialog.Overlay className="sr-overlay"/><Dialog.Content className="sr-dialog"><Dialog.Title id="award-title">Apresiasi +{award.points} poin</Dialog.Title><Dialog.Description>{award.entry.name}</Dialog.Description><label>Alasan<select autoFocus value={reason} onChange={e=>setReason(e.target.value)}>{['Menjawab','Bertanya','Diskusi','Presentasi','Membantu teman'].map(r=><option key={r}>{r}</option>)}</select></label><label>Catatan (opsional)<textarea maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></label><div><button disabled={busy} onClick={()=>setAward(null)}>Batal</button><button className="sr-primary" disabled={busy} onClick={()=>void mutate(async()=>{const rec=await pb.collection('participation_awards').create({session:selected,roster:award.entry.id,owner:pb.authStore.record?.id,points:award.points,reason,note});setUndo(()=>async()=>{await pb.collection('participation_awards').update(rec.id,{revoked:true});});setAward(null);})}>Simpan apresiasi</button></div>{error&&<p role="alert">{error}</p>}</Dialog.Content></Dialog.Portal></Dialog.Root>}
 </div>;
}
