import type { WalkthroughStep } from './workspace-guide-steps';

type Copy = [string, string, string];
const s = (selector: string, title: Copy, body: Copy, gesture: WalkthroughStep['gesture'] = 'tap'): WalkthroughStep => ({ selector, title, body, gesture });
const gradebook = [
 s('.gb-course-drop-field, .gb-head-actions .section-selector', ['Pilih kelas', 'Choose a class', 'Kurs wählen'], ['Pilih mata kuliah atau kelas yang ingin dinilai.', 'Choose the course or class to assess.', 'Wählen Sie den Kurs oder die Gruppe für die Bewertung.']),
 s('.gb-tabs .gb-tab.active', ['Nilai, komponen, analitik', 'Grades, components, analytics', 'Noten, Komponenten, Analysen'], ['Pindah tab untuk melihat nilai, mengatur komponen penilaian, atau membaca distribusi nilai.', 'Switch tabs to view grades, configure assessment components, or explore grade distributions.', 'Wechseln Sie zwischen Noten, Bewertungskomponenten und Notenverteilung.'], 'scan'),
 s('.gb-search', ['Cari mahasiswa', 'Find a student', 'Studierende finden'], ['Cari nama atau NIM sebelum meninjau nilainya.', 'Search by name or student ID before reviewing grades.', 'Suchen Sie vor der Notenprüfung nach Name oder Matrikelnummer.'], 'search'),
 s('.gb-filters', ['Temukan yang belum lengkap', 'Find incomplete grades', 'Unvollständige Noten finden'], ['Saring daftar menurut status nilai untuk menentukan mahasiswa yang perlu ditindaklanjuti.', 'Filter by grade status to identify students who need follow-up.', 'Filtern Sie nach Notenstatus, um nötige Rückmeldungen zu erkennen.']),
 s('.gb-student-btn', ['Rincian mahasiswa', 'Student details', 'Details zur Person'], ['Buka nama mahasiswa untuk meninjau rincian penilaiannya.', 'Open a student name to review assessment details.', 'Öffnen Sie einen Namen, um Bewertungsdetails anzusehen.']),
 s('.gb-td-cell', ['Nilai per komponen', 'Component scores', 'Komponentenwerte'], ['Nilai tugas dan komponen otomatis mengikuti sumbernya. Sel manual dapat diedit jika tersedia.', 'Task and automatic component scores follow their sources. Manual cells can be edited where available.', 'Aufgabenwerte und automatische Werte folgen ihren Quellen. Manuelle Felder sind bei Verfügbarkeit bearbeitbar.']),
 s('.gb-komponen-head', ['Atur komponen', 'Configure components', 'Komponenten einrichten'], ['Tambahkan atau tinjau komponen dan bobot sebelum memublikasikan nilai.', 'Add or review components and weights before publishing grades.', 'Prüfen Sie Komponenten und Gewichtungen vor der Veröffentlichung.']),
 s('.gb-dist-panel', ['Baca distribusi', 'Read the distribution', 'Verteilung lesen'], ['Grafik ini merangkum distribusi nilai kelas.', 'This chart summarizes the class grade distribution.', 'Dieses Diagramm zeigt die Notenverteilung des Kurses.'], 'scan'),
 s('.gb-publish-bar', ['Publikasikan setelah diperiksa', 'Publish after review', 'Nach Prüfung veröffentlichen'], ['Periksa kelengkapan dan bobot, lalu gunakan kontrol publikasi untuk membagikan nilai kepada mahasiswa.', 'Review completeness and weights, then use the publishing control to share grades with students.', 'Prüfen Sie Vollständigkeit und Gewichtungen, bevor Sie Noten freigeben.']),
];
const analytics = [
 s('.an-period', ['Rentang analitik', 'Analytics period', 'Analysezeitraum'], ['Pilih rentang waktu untuk membaca aktivitas kelas.', 'Choose a time range for course activity.', 'Wählen Sie einen Zeitraum für die Kursaktivität.']),
 s('.an-stats .ld-stat, .an-stats > :first-child', ['Ringkasan aktivitas', 'Activity overview', 'Aktivitätsübersicht'], ['Mulai dari indikator ringkasan, lalu baca grafik dan tabel di bawahnya.', 'Start with summary indicators, then explore the charts and tables below.', 'Beginnen Sie mit den Kennzahlen und prüfen Sie dann Diagramme und Tabellen.'], 'scan'),
 s('.an-card-head', ['Baca detail analitik', 'Explore analytics', 'Analysen ansehen'], ['Setiap panel menampilkan aspek aktivitas kelas yang berbeda. Gulir untuk membandingkannya.', 'Each panel shows a different aspect of course activity. Scroll to compare them.', 'Jeder Bereich zeigt einen anderen Aspekt der Kursaktivität. Scrollen Sie zum Vergleich.'], 'scan'),
];

const practiceSteps = [
 s('.pp-practice-course', ['Pilih mata kuliah', 'Choose a course', 'Kurs wählen'], ['Materi mata kuliah menjadi konteks latihan personal Anda.', 'Course materials provide context for your personal practice.', 'Kursmaterialien bilden den Kontext Ihrer persönlichen Übung.']),
 s('.pp-mode-switch, .cp-mode-picker', ['Jenis latihan', 'Practice mode', 'Übungsart'], ['Pilih latihan soal atau percakapan sesuai kebutuhan belajar.', 'Choose exercises or conversation for your learning needs.', 'Wählen Sie Aufgaben oder Gespräch nach Ihrem Lernbedarf.']),
 s('.pp-start .ld-btn-primary', ['Mulai latihan soal', 'Start exercises', 'Aufgaben starten'], ['Mulai lima pertanyaan yang disesuaikan dengan materi kelas.', 'Start five questions adapted to course materials.', 'Starten Sie fünf an die Kursmaterialien angepasste Fragen.']),
 s('.pp-session-grid article', ['Materi latihan', 'Practice materials', 'Übungsmaterialien'], ['Pertemuan terbaru ini menjadi sumber materi latihan.', 'These recent sessions provide practice materials.', 'Diese jüngsten Sitzungen liefern Übungsmaterialien.'], 'scan'),
 s('.pp-choices, .pp-writing', ['Jawab pertanyaan', 'Answer the question', 'Frage beantworten'], ['Pilih jawaban atau tulis tanggapan, lalu gunakan Periksa jawaban.', 'Choose an answer or write a response, then use Check answer.', 'Wählen oder schreiben Sie eine Antwort und nutzen Sie Antwort prüfen.']),
 s('.pp-feedback-explanation', ['Pelajari umpan balik', 'Learn from feedback', 'Aus Rückmeldung lernen'], ['Baca penjelasan dan rujukan sebelum melanjutkan pertanyaan berikutnya.', 'Read explanations and sources before the next question.', 'Lesen Sie Erklärungen und Quellen vor der nächsten Frage.'], 'scan'),
 s('.pp-history', ['Buka riwayat latihan', 'Open practice history', 'Übungsverlauf öffnen'], ['Buka putaran tersimpan untuk meninjau jawaban sebelumnya.', 'Open saved rounds to review previous answers.', 'Öffnen Sie gespeicherte Runden für frühere Antworten.']),
 s('.cp-live-controls', ['Mulai atau jeda mikrofon', 'Start or pause the microphone', 'Mikrofon starten oder pausieren'], ['Aktifkan mikrofon untuk berbicara. Gunakan Jeda untuk berhenti mendengarkan.', 'Enable the microphone to speak. Use Pause to stop listening.', 'Aktivieren Sie das Mikrofon zum Sprechen. Pause beendet das Zuhören.']),
 s('.cp-transcript-heading', ['Transkrip di samping', 'Transcript alongside', 'Transkript daneben'], ['Ucapan yang selesai muncul di kolom transkrip. Sesi berakhir setelah enam jawaban.', 'Completed utterances appear in the transcript column. A session ends after six answers.', 'Abgeschlossene Äußerungen erscheinen im Transkript. Eine Sitzung endet nach sechs Antworten.'], 'scan'),
 s('.cp-type-fallback summary', ['Jawaban ketik', 'Typed answers', 'Getippte Antworten'], ['Buka pilihan ini jika ingin berlatih melalui jawaban ketik.', 'Open this option to practise with typed answers.', 'Öffnen Sie diese Option für getippte Antworten.']),
 s('.cp-summary', ['Refleksi sesi', 'Session reflection', 'Sitzungsreflexion'], ['Tinjau rangkuman sesi. Percakapan selesai dapat dibaca kembali di profil belajar.', 'Review the session summary. Completed conversations can be revisited in your learning profile.', 'Prüfen Sie die Zusammenfassung. Abgeschlossene Gespräche finden Sie im Lernprofil wieder.'], 'scan'),
];

export function dedicatedPageSteps(path: string, student: boolean): WalkthroughStep[] | undefined {
 const route = path.split('#')[0].replace(/\/$/, '');
 const course = route.match(/^\/app\/courses\/[^/]+(?:\/(.*))?$/);
 if (course) {
  const section = course[1] || 'ringkasan';
  const rail = [s('.ld-course-switch-btn, .ld-course-rail-head', ['Mata kuliah aktif', 'Current course', 'Aktueller Kurs'], ['Periksa nama mata kuliah di sini. Dosen dapat membuka pemilih untuk berpindah mata kuliah.', 'Check the course name here. Instructors can open the picker to switch courses.', 'Prüfen Sie hier den Kursnamen. Lehrkräfte können über die Auswahl den Kurs wechseln.']), s('.ld-course-rail-link.active', ['Bagian mata kuliah', 'Course sections', 'Kursbereiche'], ['Menu kelas memisahkan pertemuan, berkas, tugas, nilai, dan informasi. Buka Panduan lagi setelah berpindah bagian.', 'The course menu separates sessions, files, tasks, grades, and information. Reopen Guide after switching sections.', 'Das Kursmenü trennt Sitzungen, Dateien, Aufgaben, Noten und Informationen. Öffnen Sie die Anleitung nach einem Wechsel erneut.'], 'scan')];
  let content: WalkthroughStep[] = [];
  if (section === 'ringkasan') content = student ? [
   s('.sco-progress-card', ['Progres kelas', 'Course progress', 'Kursfortschritt'], ['Lihat progres pertemuan dan buka rincian kelas dari tautan yang tersedia.', 'Check session progress and open the available course details.', 'Prüfen Sie den Sitzungsfortschritt und öffnen Sie die Kursdetails.'], 'scan'),
   s('.sco-next', ['Pertemuan berikutnya', 'Next session', 'Nächste Sitzung'], ['Baca topik dan materi untuk mempersiapkan pertemuan berikutnya.', 'Read the topic and materials to prepare for your next session.', 'Lesen Sie Thema und Materialien zur Vorbereitung auf die nächste Sitzung.'], 'scan'),
   s('.sco-task-cta', ['Kerjakan tugas', 'Work on a task', 'Aufgabe bearbeiten'], ['Buka tugas untuk membaca instruksi dan mengirim pekerjaan.', 'Open a task to read instructions and submit your work.', 'Öffnen Sie eine Aufgabe für Anweisungen und Abgabe.']),
   s('.student-course-practice .sd-game-primary', ['Latihan personal', 'Personal practice', 'Persönliche Übungen'], ['Mulai latihan berdasarkan materi mata kuliah ini.', 'Start practice based on this course’s materials.', 'Starten Sie Übungen anhand der Materialien dieses Kurses.']),
  ] : [
   s('.cw-page-head-actions', ['Kelola kelas', 'Manage the course', 'Kurs verwalten'], ['Aksi di sini membuka pengelolaan RPS dan detail mata kuliah.', 'These actions open syllabus and course details management.', 'Hier öffnen Sie die Verwaltung von Lehrplan und Kursdetails.']),
   s('.cw-review-head', ['Periksa kesiapan', 'Check readiness', 'Bereitschaft prüfen'], ['Buka pemeriksaan untuk melihat bagian RPS yang masih perlu dilengkapi.', 'Open the review to find syllabus sections that still need attention.', 'Öffnen Sie die Prüfung für noch unvollständige Lehrplanbereiche.']),
   s('.cw-week-timeline, .cw-week-chips', ['Rencana pertemuan', 'Session plan', 'Sitzungsplan'], ['Ringkasan mingguan membantu memeriksa urutan pertemuan kelas.', 'The weekly overview helps you check the course session sequence.', 'Die Wochenübersicht zeigt die Reihenfolge der Kurssitzungen.'], 'scan'),
   s('.cw-quick-grid', ['Jalur cepat', 'Quick access', 'Schnellzugriff'], ['Gunakan pintasan untuk masuk ke materi, tugas, atau bagian kelas lainnya.', 'Use shortcuts to open materials, tasks, or other course sections.', 'Nutzen Sie Verknüpfungen zu Materialien, Aufgaben und weiteren Kursbereichen.']),
  ];
  else if (section === 'nilai') content = student ? [
   s('.sgr-summary', ['Ringkasan nilai', 'Grade summary', 'Notenübersicht'], ['Lihat ringkasan nilai yang telah dibagikan dosen.', 'View the grades shared by your instructor.', 'Sehen Sie die von Ihrer Lehrkraft freigegebenen Noten.'], 'scan'),
   s('.sgr-row-main', ['Hasil per tugas', 'Results by task', 'Ergebnisse je Aufgabe'], ['Pilih tugas untuk membaca hasil dan umpan baliknya.', 'Choose a task to read results and feedback.', 'Wählen Sie eine Aufgabe für Ergebnisse und Rückmeldungen.']),
   s('.pp-profile-skills', ['Perkembangan kemampuan', 'Skill development', 'Kompetenzentwicklung'], ['Baca indikator kemampuan sebagai bahan refleksi belajar.', 'Read skill indicators for learning reflection.', 'Lesen Sie Kompetenzindikatoren zur Lernreflexion.'], 'scan'),
  ] : gradebook;
  else if (section === 'analitik') content = analytics;
  else if (section === 'berkas') content = [
   s('.res-area .ld-btn-primary', ['Tambah materi kelas', 'Add course materials', 'Kursmaterial hinzufügen'], ['Unggah atau pilih berkas untuk dibagikan di mata kuliah ini.', 'Upload or select files to share in this course.', 'Laden Sie Dateien hoch oder wählen Sie Dateien für diesen Kurs.']),
   s('.res-group-head', ['Materi per pertemuan', 'Materials by session', 'Materialien pro Sitzung'], ['Berkas dikelompokkan agar materi pertemuan mudah ditemukan.', 'Files are grouped so session materials are easy to find.', 'Dateien sind gruppiert, damit Sitzungsmaterial leicht zu finden ist.'], 'scan'),
   s('.res-row', ['Baca materi', 'Read materials', 'Materialien lesen'], ['Periksa judul dan informasi berkas sebelum membukanya.', 'Check the file title and details before opening it.', 'Prüfen Sie Titel und Dateiinformationen vor dem Öffnen.'], 'scan'),
   s('.res-actions', ['Buka atau unduh', 'Open or download', 'Öffnen oder herunterladen'], ['Gunakan aksi pada baris berkas untuk membuka, mengunduh, atau mengelola materi sesuai izin Anda.', 'Use the file row actions to open, download, or manage materials according to your permissions.', 'Öffnen, laden oder verwalten Sie Materialien über die Zeilenaktionen entsprechend Ihren Rechten.']),
  ];
  else if (section === 'mata-kuliah') content = [
   s('.ld-sessions-actions .ld-btn-primary', ['Tambah pertemuan', 'Add a session', 'Sitzung hinzufügen'], ['Siapkan topik dan jadwal pertemuan melalui tombol ini.', 'Set up session topics and dates here.', 'Legen Sie hier Sitzungsthemen und Termine an.']),
   s('.ld-session-desc', ['Topik dan materi', 'Topics and materials', 'Themen und Materialien'], ['Baca topik, catatan, dan materi pada setiap pertemuan.', 'Read the topic, notes, and materials for each session.', 'Lesen Sie Thema, Hinweise und Materialien jeder Sitzung.'], 'scan'),
   s('.ld-session-desc .ld-text-btn', ['Rencana pembelajaran', 'Lesson plan', 'Unterrichtsplan'], ['Buka rencana pembelajaran untuk menyiapkan kegiatan pertemuan.', 'Open the lesson plan to prepare session activities.', 'Öffnen Sie den Unterrichtsplan zur Vorbereitung der Aktivitäten.']),
   s('.ld-session-actions, .ld-session-check', ['Kelola pertemuan', 'Manage sessions', 'Sitzungen verwalten'], ['Gunakan kontrol pertemuan yang tersedia sesuai peran Anda.', 'Use the session controls available to your role.', 'Nutzen Sie die für Ihre Rolle verfügbaren Sitzungsaktionen.']),
  ];
  else if (section === 'absensi') content = [
   s('.sr-toolbar select[aria-label="Kelas"]', ['Pilih kelas', 'Choose a class', 'Gruppe wählen'], ['Pilih kelas paralel sebelum mencatat kehadiran.', 'Choose a class group before recording attendance.', 'Wählen Sie vor der Anwesenheitserfassung eine Gruppe.']),
   s('.sr-toolbar select[aria-label="Pertemuan"]', ['Pilih pertemuan', 'Choose a session', 'Sitzung wählen'], ['Pastikan pertemuan yang dipilih sesuai dengan sesi yang sedang berlangsung.', 'Make sure the selected session matches the current meeting.', 'Prüfen Sie, ob die gewählte Sitzung dem aktuellen Termin entspricht.']),
   s('.sr-toolbar input', ['Cari mahasiswa', 'Find students', 'Studierende finden'], ['Cari nama atau NIM untuk mempersempit daftar absensi.', 'Search by name or ID to narrow the attendance list.', 'Suchen Sie nach Name oder Matrikelnummer.'], 'search'),
   s('.sr-status', ['Catat kehadiran', 'Record attendance', 'Anwesenheit erfassen'], ['Pilih status kehadiran mahasiswa pada barisnya.', 'Choose attendance status in each student’s row.', 'Wählen Sie den Anwesenheitsstatus in der jeweiligen Zeile.']),
   s('.sr-points', ['Apresiasi partisipasi', 'Recognize participation', 'Beteiligung anerkennen'], ['Tambahkan poin keaktivan dengan alasan saat mahasiswa berpartisipasi.', 'Award participation points with a reason when students contribute.', 'Vergeben Sie bei Beiträgen Beteiligungspunkte mit Begründung.']),
   s('.sr-footer', ['Selesaikan pencatatan', 'Finish recording', 'Erfassung abschließen'], ['Lengkapi kehadiran lalu selesaikan pencatatan. Buka kembali bila perlu koreksi.', 'Complete attendance and finish recording. Reopen if corrections are needed.', 'Vervollständigen Sie die Anwesenheit und schließen Sie die Erfassung ab. Für Korrekturen erneut öffnen.']),
   s('.ld-attendance-summary', ['Kehadiran Anda', 'Your attendance', 'Ihre Anwesenheit'], ['Ringkasan ini menunjukkan kehadiran yang telah dicatat dosen.', 'This summary shows attendance recorded by your instructor.', 'Diese Übersicht zeigt die von Ihrer Lehrkraft erfasste Anwesenheit.'], 'scan'),
  ];
  else if (section === 'mahasiswa') content = [
   s('.roster-head-actions', ['Kelola daftar mahasiswa', 'Manage the roster', 'Teilnehmende verwalten'], ['Tambahkan atau impor daftar mahasiswa lewat aksi di sini.', 'Add or import students using these actions.', 'Fügen Sie Studierende über diese Aktionen hinzu oder importieren Sie sie.']),
   s('.roster-profile-link', ['Buka profil belajar', 'Open a learning profile', 'Lernprofil öffnen'], ['Klik nama untuk melihat progres dan aktivitas mahasiswa.', 'Open a name to view the student’s progress and activity.', 'Öffnen Sie einen Namen für Lernfortschritt und Aktivitäten.']),
   s('.roster-td-status', ['Periksa status akun', 'Check account status', 'Kontostatus prüfen'], ['Status ini membantu memeriksa akses mahasiswa ke kelas.', 'This status helps you check student access to the class.', 'Dieser Status hilft beim Prüfen des Kurszugangs.'], 'scan'),
   s('.roster-language-select', ['Bahasa pembelajaran', 'Learning language', 'Lernsprache'], ['Atur bahasa yang tersedia untuk mahasiswa pada daftar ini.', 'Set the available student language in this roster.', 'Stellen Sie die verfügbare Sprache in dieser Liste ein.']),
  ];
  else if (section === 'tugas') content = [
   s('.asg-area > header .ld-btn-primary, .asg-area .ld-btn-primary', ['Siapkan tugas', 'Prepare a task', 'Aufgabe vorbereiten'], ['Buka penyusunan tugas untuk menentukan instruksi, batas waktu, dan penilaian.', 'Open task creation to set instructions, deadlines, and assessment.', 'Öffnen Sie die Aufgabenerstellung für Anweisungen, Fristen und Bewertung.']),
   s('.asg-card-title-wrap', ['Pilih tugas', 'Choose a task', 'Aufgabe wählen'], ['Periksa judul dan status tugas sebelum membukanya.', 'Check task titles and status before opening them.', 'Prüfen Sie Titel und Status vor dem Öffnen.'], 'scan'),
   s('.asg-instructions', ['Baca instruksi', 'Read instructions', 'Anweisungen lesen'], ['Baca instruksi dan persyaratan berkas sebelum mengerjakan atau menilai tugas.', 'Read instructions and file requirements before working on or assessing a task.', 'Lesen Sie Anweisungen und Dateianforderungen vor Bearbeitung oder Bewertung.'], 'scan'),
   s('.asg-form-actions', ['Kirim pekerjaan', 'Submit your work', 'Arbeit abgeben'], ['Periksa jawaban dan lampiran sebelum mengirim pekerjaan.', 'Check your answer and attachments before submitting.', 'Prüfen Sie Antwort und Anhänge vor der Abgabe.']),
   s('.asg-actions', ['Aksi tugas', 'Task actions', 'Aufgabenaktionen'], ['Buka atau kelola tugas lewat kontrol yang tersedia di kartu ini.', 'Open or manage the task using the controls on this card.', 'Öffnen oder verwalten Sie die Aufgabe über diese Karte.']),
  ];
  else if (section === 'rps' || section === 'silabus') content = [
   s('.ld-rps-head .ld-btn-primary, .ld-document-side .ld-outline-action', ['Kelola dokumen', 'Manage the document', 'Dokument verwalten'], ['Dosen dapat membuka editor untuk memperbarui dokumen kelas.', 'Instructors can open the editor to update the course document.', 'Lehrkräfte können den Editor zur Aktualisierung öffnen.']),
   s('.ld-rps-summary, .ld-document-paper-header', ['Ringkasan dokumen', 'Document overview', 'Dokumentübersicht'], ['Periksa identitas dan ringkasan sebelum membaca detailnya.', 'Check the identity and overview before reading details.', 'Prüfen Sie Identität und Übersicht vor den Details.'], 'scan'),
   s('.ld-structured-head, .ld-syllabus-topic', ['Capaian dan topik', 'Outcomes and topics', 'Lernziele und Themen'], ['Baca capaian, topik, dan rencana pembelajaran yang digunakan dalam kelas.', 'Read the outcomes, topics, and learning plan used in class.', 'Lesen Sie Lernziele, Themen und Lernplan des Kurses.'], 'scan'),
   s('.ld-source-document summary, .ld-document-paper-footer', ['Dokumen sumber', 'Source document', 'Quelldokument'], ['Lihat dokumen sumber dan tautan unduhan yang tersedia.', 'View the source document and available downloads.', 'Sehen Sie Quelldokument und verfügbare Downloads an.']),
  ];
  else if (section === 'pengaturan') content = [s('.course-settings-grid', ['Identitas mata kuliah', 'Course identity', 'Kursdaten'], ['Perbarui detail mata kuliah pada kolom yang tersedia.', 'Update course details in the available fields.', 'Aktualisieren Sie die Kursdaten in den Feldern.'], 'scan'), s('.course-settings .ld-btn-primary', ['Simpan perubahan', 'Save changes', 'Änderungen speichern'], ['Periksa isian lalu simpan untuk menerapkan perubahan.', 'Review the fields and save to apply changes.', 'Prüfen und speichern Sie die Angaben.'])];
  else if (section === 'latihan') content = practiceSteps;
  else if (section === 'info') content = [s('.sci-grid', ['Informasi kelas', 'Class information', 'Kursinformationen'], ['Lihat identitas, dosen, dan informasi pembelajaran kelas.', 'Review course identity, instructor, and learning information.', 'Prüfen Sie Kursdaten, Lehrkraft und Lerninformationen.'], 'scan'), s('.sci-shortcuts', ['Buka rincian', 'Open details', 'Details öffnen'], ['Pintasan ini membawa Anda ke bagian kelas yang terkait.', 'These shortcuts open related course sections.', 'Diese Verknüpfungen öffnen zugehörige Kursbereiche.'])];
  else if (section.includes('/rencana')) content = [s('.lp-tabs', ['Bagian rencana', 'Plan sections', 'Planbereiche'], ['Pilih bagian rencana pembelajaran yang ingin disusun.', 'Choose the lesson plan section to prepare.', 'Wählen Sie den zu bearbeitenden Planbereich.']), s('.lp-card', ['Susun kegiatan', 'Prepare activities', 'Aktivitäten vorbereiten'], ['Lengkapi kegiatan dan informasi pertemuan dalam editor ini.', 'Complete activities and session information in this editor.', 'Ergänzen Sie Aktivitäten und Sitzungsinformationen.'], 'scan'), s('.lp-save', ['Simpan rencana', 'Save the plan', 'Plan speichern'], ['Simpan rencana setelah memeriksa isinya.', 'Save the plan after reviewing its contents.', 'Speichern Sie den Plan nach Prüfung.'])];
  else if (section.startsWith('mahasiswa/')) content = [s('.sp-header', ['Profil mahasiswa', 'Student profile', 'Studierendenprofil'], ['Pastikan mahasiswa dan kelas yang sedang Anda tinjau.', 'Check the student and course you are reviewing.', 'Prüfen Sie die Person und den Kurs.'], 'scan'), s('.sp-metrics', ['Progres belajar', 'Learning progress', 'Lernfortschritt'], ['Baca indikator progres lalu tinjau aktivitas di bawahnya.', 'Read progress indicators and review activities below.', 'Lesen Sie die Kennzahlen und prüfen Sie die Aktivitäten darunter.'], 'scan'), s('.sp-task-list', ['Riwayat tugas', 'Task history', 'Aufgabenverlauf'], ['Buka tugas terkait untuk meninjau pekerjaan dan tindak lanjut.', 'Open related tasks to review work and follow-up.', 'Öffnen Sie Aufgaben zur Prüfung der Arbeit und Rückmeldung.'])];
  return [...rail, ...content];
 }
 if (route === '/app/latihan') return practiceSteps;
 if (route === '/app/penilaian') return gradebook;
 if (route === '/app/berkas') return [
  s('.flb-page .ld-search-bar', ['Cari berkas', 'Find a file', 'Datei finden'], ['Cari nama berkas untuk mempersempit pustaka.', 'Search file names to narrow the library.', 'Suchen Sie Dateinamen in der Bibliothek.'], 'search'),
  s('.flb-filters', ['Saring pustaka', 'Filter the library', 'Bibliothek filtern'], ['Gunakan filter untuk menemukan jenis berkas dan hubungan kelas yang sesuai.', 'Use filters to find matching file types and course links.', 'Filtern Sie nach Dateityp und Kurszuordnung.']),
  s('.flb-page .ld-courses-actions .ld-btn-primary', ['Unggah berkas', 'Upload files', 'Dateien hochladen'], ['Tambahkan berkas ke pustaka lalu kaitkan dengan kelas sesuai kebutuhan.', 'Add files to the library and link them to classes as needed.', 'Fügen Sie Dateien hinzu und ordnen Sie sie Kursen zu.']),
  s('.flb-row .flb-main', ['Periksa informasi berkas', 'Check file information', 'Dateiinformationen prüfen'], ['Lihat judul, status pemrosesan, dan hubungan mata kuliah pada baris ini.', 'Review the title, processing status, and course links in this row.', 'Prüfen Sie Titel, Verarbeitungsstatus und Kurszuordnung.'], 'scan'),
  s('.flb-actions [aria-label^="Pratinjau"], .flb-actions [aria-label^="Unduh"]', ['Baca berkas', 'Read the file', 'Datei lesen'], ['Buka pratinjau atau unduh salinan melalui aksi berkas.', 'Open a preview or download a copy using file actions.', 'Öffnen Sie eine Vorschau oder laden Sie eine Kopie herunter.']),
  s('.flb-actions [aria-label^="Konteks"]', ['Konteks untuk AI', 'Context for AI', 'Kontext für KI'], ['Buka Konteks untuk memeriksa isi yang dipakai AI dan hubungan materi dengan kelas.', 'Open Context to review content used by AI and its course links.', 'Öffnen Sie Kontext, um KI-Inhalte und Kurszuordnung zu prüfen.']),
 ];
 if (route.startsWith('/app/berkas/')) return [s('.fcx-source', ['Periksa sumber', 'Check the source', 'Quelle prüfen'], ['Lihat informasi sumber berkas sebelum mengatur konteksnya.', 'Review source information before configuring context.', 'Prüfen Sie Quelldaten vor der Kontexteinstellung.'], 'scan'), s('.fcx-text-fold summary', ['Teks hasil pemrosesan', 'Processed text', 'Verarbeiteter Text'], ['Buka hasil ekstraksi untuk memeriksa teks yang terbaca.', 'Open extracted text to check what was read.', 'Öffnen Sie den extrahierten Text zur Prüfung.']), s('.fcx-suggest', ['Tinjau saran konteks', 'Review context suggestions', 'Kontextvorschläge prüfen'], ['Periksa saran sebelum menyetujui atau menolaknya.', 'Review suggestions before accepting or rejecting them.', 'Prüfen Sie Vorschläge vor Annahme oder Ablehnung.']), s('.fcx-grid2', ['Atur konteks', 'Configure context', 'Kontext einstellen'], ['Lengkapi informasi berkas dan hubungan materi dengan kelas.', 'Complete file information and course material links.', 'Ergänzen Sie Dateiinformationen und Kurszuordnung.'], 'scan'), s('.fcx-toggle', ['Penggunaan oleh AI', 'AI usage', 'KI-Verwendung'], ['Periksa tanda konteks AI sebelum menyimpan perubahan.', 'Review AI context flags before saving changes.', 'Prüfen Sie KI-Kontextmarkierungen vor dem Speichern.'])];
 if (route === '/app' || route === '/app/student') return student ? [s('.sd-resume-cta', ['Lanjutkan belajar', 'Resume learning', 'Weiterlernen'], ['Lanjutkan aktivitas kelas terakhir dari sini.', 'Resume your recent course activity here.', 'Setzen Sie hier die letzte Kursaktivität fort.']), s('.sd-game-task-action', ['Tugas yang menunggu', 'Pending tasks', 'Offene Aufgaben'], ['Buka pengingat tugas untuk melihat pekerjaan yang perlu diselesaikan.', 'Open task reminders to see work that needs completing.', 'Öffnen Sie Aufgabenerinnerungen für ausstehende Arbeit.']), s('.sd-course-head', ['Masuk ke kelas', 'Open a class', 'Kurs öffnen'], ['Pilih mata kuliah untuk melihat pertemuan, materi, dan tugas.', 'Choose a course for sessions, materials, and tasks.', 'Wählen Sie einen Kurs für Sitzungen, Materialien und Aufgaben.']), s('#progres-belajar', ['Tinjau progres', 'Review progress', 'Fortschritt prüfen'], ['Baca progres belajar untuk merencanakan latihan berikutnya.', 'Review learning progress to plan your next practice.', 'Prüfen Sie Ihren Fortschritt zur Planung weiterer Übungen.'], 'scan')] : [s('.ld-greet-chat .asst-input', ['Minta bantuan Laras', 'Ask Laras for help', 'Laras um Hilfe bitten'], ['Tulis kebutuhan mengajar Anda untuk memulai percakapan dengan asisten.', 'Describe your teaching needs to start an assistant conversation.', 'Beschreiben Sie Ihren Lehrbedarf für ein Gespräch mit dem Assistenten.'], 'search'), s('.ld-action-row', ['Aksi cepat', 'Quick actions', 'Schnellaktionen'], ['Gunakan pintasan untuk membuka pekerjaan utama Anda.', 'Use shortcuts to open your main workflows.', 'Nutzen Sie Verknüpfungen für Ihre wichtigsten Aufgaben.']), s('.ld-grading-row', ['Tinjau pekerjaan mahasiswa', 'Review student work', 'Studierendenarbeit prüfen'], ['Buka tugas yang memerlukan peninjauan dari daftar ini.', 'Open tasks needing review from this list.', 'Öffnen Sie hier Aufgaben, die geprüft werden müssen.']), s('.ld-schedule-list', ['Jadwal kelas', 'Class schedule', 'Kursplan'], ['Periksa jadwal sebelum membuka mata kuliah terkait.', 'Check the schedule before opening the related course.', 'Prüfen Sie Termine vor dem Öffnen des zugehörigen Kurses.'], 'scan')];
 if (route === '/app/tugas') return [s('.eval-board .mk-search', ['Cari tugas', 'Find a task', 'Aufgabe finden'], ['Cari judul tugas dalam daftar ini.', 'Search task titles in this list.', 'Suchen Sie Aufgabentitel in dieser Liste.'], 'search'), s('.eval-board .mk-select', ['Saring daftar', 'Filter tasks', 'Aufgaben filtern'], ['Saring tugas menurut pilihan yang tersedia, termasuk mata kuliah.', 'Filter tasks using the available options, including course.', 'Filtern Sie Aufgaben nach den verfügbaren Optionen, einschließlich Kurs.']), s('.eval-board .mk-create', ['Buat tugas', 'Create a task', 'Aufgabe erstellen'], ['Buka editor untuk menyusun tugas kelas.', 'Open the editor to prepare a class task.', 'Öffnen Sie den Editor für eine Kursaufgabe.']), s('.eval-board-main', ['Buka peninjauan', 'Open review', 'Prüfung öffnen'], ['Pilih tugas untuk membaca pekerjaan mahasiswa dan meninjaunya.', 'Choose a task to read and review student work.', 'Wählen Sie eine Aufgabe zur Prüfung der Studierendenarbeit.'])];
 if (route === '/app/tugas/buat') return [s('.asg-wsummary', ['Identitas tugas', 'Task identity', 'Aufgabendaten'], ['Periksa ringkasan kelas dan tugas yang sedang disusun.', 'Check the course and task summary.', 'Prüfen Sie die Kurs- und Aufgabenübersicht.'], 'scan'), s('.asg-type-grid', ['Bentuk tugas', 'Task format', 'Aufgabenformat'], ['Pilih bentuk pekerjaan yang diminta dari mahasiswa.', 'Choose the work format required from students.', 'Wählen Sie das verlangte Arbeitsformat.']), s('.asg-section', ['Susun instruksi', 'Prepare instructions', 'Anweisungen vorbereiten'], ['Lengkapi isian editor, instruksi, dan pengaturan penilaian sebelum menyimpan.', 'Complete editor fields, instructions, and assessment settings before saving.', 'Ergänzen Sie Felder, Anweisungen und Bewertungseinstellungen vor dem Speichern.'], 'scan'), s('.asg-preview', ['Periksa pratinjau', 'Review the preview', 'Vorschau prüfen'], ['Tinjau tampilan tugas sebelum menyimpannya.', 'Review the task preview before saving.', 'Prüfen Sie die Aufgabenvorschau vor dem Speichern.'])];
 if (route.endsWith('/pratinjau')) return [s('.lap-tabs', ['Tampilan mahasiswa', 'Student view', 'Studierendenansicht'], ['Pindah tab untuk melihat tampilan tugas dan hasil dari sisi mahasiswa.', 'Switch tabs to preview tasks and results as a student.', 'Wechseln Sie zwischen Aufgaben- und Ergebnisvorschau aus Studierendensicht.']), s('.lap-text', ['Periksa instruksi', 'Review instructions', 'Anweisungen prüfen'], ['Baca instruksi seperti yang akan dilihat mahasiswa.', 'Read instructions as students will see them.', 'Lesen Sie die Anweisungen aus Studierendensicht.'], 'scan'), s('.lap-answer-format', ['Format jawaban', 'Answer format', 'Antwortformat'], ['Periksa format pekerjaan sebelum kembali ke editor.', 'Check the answer format before returning to the editor.', 'Prüfen Sie das Antwortformat vor der Rückkehr zum Editor.'])];
 if (route === '/app/tugas/insights') return [s('.eval-head', ['Wawasan tugas', 'Task insights', 'Aufgabenanalyse'], ['Periksa konteks tugas yang sedang dianalisis.', 'Check the task context being analyzed.', 'Prüfen Sie den analysierten Aufgabenkontext.'], 'scan'), ...analytics];
 if (route.startsWith('/app/kerja/')) return [s('.sas-identity', ['Identitas pekerjaan', 'Work identity', 'Arbeitsdaten'], ['Pastikan tugas dan identitas sebelum mengerjakan.', 'Check task and identity before starting.', 'Prüfen Sie Aufgabe und Identität vor Beginn.'], 'scan'), s('.sas-answer', ['Kerjakan jawaban', 'Prepare your answer', 'Antwort bearbeiten'], ['Isi jawaban dan lampiran sesuai instruksi tugas.', 'Complete your response and attachments according to the instructions.', 'Ergänzen Sie Antwort und Anhänge gemäß den Anweisungen.']), s('.sas-review', ['Periksa sebelum mengirim', 'Review before submission', 'Vor Abgabe prüfen'], ['Periksa pekerjaan sebelum mengirimnya.', 'Review your work before submitting.', 'Prüfen Sie Ihre Arbeit vor der Abgabe.']), s('.srs-script', ['Baca hasil pekerjaan', 'Read your results', 'Ergebnisse lesen'], ['Tinjau pekerjaan tersimpan dan catatan yang tersedia.', 'Review saved work and available comments.', 'Prüfen Sie gespeicherte Arbeit und Kommentare.'], 'scan'), s('.srs-rec-card', ['Umpan balik', 'Feedback', 'Rückmeldung'], ['Gunakan catatan dan rekomendasi untuk refleksi dan perbaikan.', 'Use comments and recommendations for reflection and improvement.', 'Nutzen Sie Hinweise und Empfehlungen zur Reflexion und Verbesserung.'])];
 if (route.startsWith('/app/tugas/')) return [s('.eval-head', ['Tugas yang ditinjau', 'Task under review', 'Geprüfte Aufgabe'], ['Pastikan judul dan kelas tugas yang sedang dinilai.', 'Check the title and course of the task being assessed.', 'Prüfen Sie Titel und Kurs der bewerteten Aufgabe.'], 'scan'), s('.cho-search', ['Cari peserta', 'Find participants', 'Teilnehmende finden'], ['Cari mahasiswa untuk membuka pekerjaannya.', 'Find a student to open their work.', 'Suchen Sie eine Person zum Öffnen ihrer Arbeit.'], 'search'), s('.eval-people', ['Pilih mahasiswa', 'Choose a student', 'Person wählen'], ['Pilih mahasiswa dari daftar untuk meninjau jawaban dan statusnya.', 'Select a student to review their response and status.', 'Wählen Sie eine Person für Antwort und Status.']), s('.eval-tabs', ['Jawaban dan riwayat', 'Response and history', 'Antwort und Verlauf'], ['Pindah tab untuk membaca jawaban dan riwayat pekerjaan.', 'Switch tabs to read responses and work history.', 'Wechseln Sie zwischen Antwort und Arbeitsverlauf.']), s('.evx-final-block', ['Tinjau nilai akhir', 'Review the final score', 'Endwert prüfen'], ['Periksa temuan dan nilai sebelum menyimpan atau memublikasikan hasil.', 'Review findings and scores before saving or publishing results.', 'Prüfen Sie Befunde und Werte vor Speicherung oder Veröffentlichung.']), s('.evx-actions', ['Simpan hasil peninjauan', 'Save review results', 'Prüfergebnis speichern'], ['Gunakan aksi yang tersedia setelah peninjauan selesai.', 'Use the available actions when your review is complete.', 'Nutzen Sie die verfügbaren Aktionen nach Abschluss der Prüfung.'])];
 if (route.startsWith('/app/rps/')) return [s('.rps-upload-panel', ['Mulai dari dokumen', 'Start with a document', 'Mit Dokument beginnen'], ['Unggah RPS yang tersedia untuk membantu mengisi editor.', 'Upload an existing syllabus to help populate the editor.', 'Laden Sie einen vorhandenen Lehrplan als Grundlage hoch.']), s('.rps-step-title', ['Tahap penyusunan', 'Setup stage', 'Bearbeitungsschritt'], ['Judul ini menunjukkan tahap RPS yang sedang Anda lengkapi.', 'This title identifies the syllabus stage you are completing.', 'Dieser Titel zeigt den aktuellen Bearbeitungsschritt.'], 'scan'), s('.rps-step-body .rps-card, .rps-step-body', ['Isi RPS', 'Complete the syllabus', 'Lehrplan ausfüllen'], ['Lengkapi kolom pada tahap ini sebelum beralih ke tahap berikutnya.', 'Complete fields in this stage before moving to the next.', 'Füllen Sie die Felder aus, bevor Sie zum nächsten Schritt gehen.'], 'scan'), s('.rps-step-footer', ['Berpindah tahap', 'Move between stages', 'Schritt wechseln'], ['Gunakan navigasi tahap untuk kembali, melanjutkan, atau menyimpan RPS.', 'Use stage navigation to go back, continue, or save the syllabus.', 'Gehen Sie zurück, weiter oder speichern Sie den Lehrplan.'])];
 if (route === '/app/pengaturan') return [s('.ld-settings-avatar', ['Profil akun', 'Account profile', 'Kontoprofil'], ['Perbarui foto dan informasi profil pada bagian ini.', 'Update your photo and profile information here.', 'Aktualisieren Sie hier Foto und Profilinformationen.']), s('.ld-settings-seg', ['Bahasa dan tampilan', 'Language and appearance', 'Sprache und Darstellung'], ['Pilih preferensi antarmuka melalui pilihan yang tersedia.', 'Choose interface preferences using these controls.', 'Wählen Sie Ihre Oberflächeneinstellungen.']), s('.sp-preferences-panel .ld-settings-form-grid', ['Preferensi belajar', 'Learning preferences', 'Lernpräferenzen'], ['Sesuaikan bahasa penjelasan dan bantuan yang Anda butuhkan.', 'Customize explanation language and the help you need.', 'Passen Sie Erklärungssprache und gewünschte Hilfe an.']), s('.sp-consent-row', ['Kendalikan berbagi profil', 'Control profile sharing', 'Profilfreigabe steuern'], ['Periksa pilihan berbagi profil belajar dan personalisasi AI.', 'Review learning profile sharing and AI personalization choices.', 'Prüfen Sie Lernprofilfreigabe und KI-Personalisierung.']), s('.cp-profile-reflections', ['Refleksi percakapan', 'Conversation reflections', 'Gesprächsreflexionen'], ['Buka sesi tersimpan untuk membaca transkrip dan refleksi percakapan.', 'Open saved sessions to read transcripts and conversation reflections.', 'Öffnen Sie gespeicherte Sitzungen für Transkripte und Reflexionen.'], 'scan')];
 if (route === '/app/asisten') return [s('.asst-session-add, .asst-session-new', ['Percakapan baru', 'New conversation', 'Neues Gespräch'], ['Mulai percakapan terpisah untuk kebutuhan baru.', 'Start a separate conversation for a new need.', 'Beginnen Sie für ein neues Anliegen ein separates Gespräch.']), s('.asst-session-search', ['Cari riwayat', 'Search history', 'Verlauf durchsuchen'], ['Temukan percakapan lama melalui pencarian.', 'Find past conversations using search.', 'Finden Sie frühere Gespräche über die Suche.'], 'search'), s('.asst-context-bar', ['Periksa konteks', 'Check context', 'Kontext prüfen'], ['Konteks ini menunjukkan kelas atau halaman yang digunakan asisten.', 'This context shows the class or page used by the assistant.', 'Dieser Kontext zeigt den Kurs oder die Seite des Assistenten.'], 'scan'), s('.asst-input', ['Tulis permintaan', 'Write a request', 'Anfrage schreiben'], ['Jelaskan kebutuhan Anda, lalu kirim melalui tombol pada kolom pesan.', 'Describe your needs and send using the message control.', 'Beschreiben Sie Ihr Anliegen und senden Sie es über das Nachrichtenfeld.'], 'search'), s('.asst-thread', ['Tinjau tanggapan', 'Review responses', 'Antworten prüfen'], ['Baca tanggapan dan periksa tindakan yang memerlukan konfirmasi.', 'Read responses and review actions requiring confirmation.', 'Lesen Sie Antworten und prüfen Sie bestätigungspflichtige Aktionen.'], 'scan')];
 if (route === '/kalender') return [s('.ac2-views', ['Pilih tampilan', 'Choose a view', 'Ansicht wählen'], ['Ganti tampilan bulan, minggu, atau daftar sesuai kebutuhan.', 'Switch between month, week, and list views.', 'Wechseln Sie zwischen Monats-, Wochen- und Listenansicht.']), s('.ac2-nav-title', ['Pindah periode', 'Change period', 'Zeitraum wechseln'], ['Gunakan panah untuk melihat periode sebelumnya atau berikutnya.', 'Use arrows to see previous or next periods.', 'Nutzen Sie die Pfeile für vorige oder nächste Zeiträume.']), s('.ac2-filters', ['Saring kegiatan', 'Filter events', 'Termine filtern'], ['Pilih kategori kegiatan yang ingin ditampilkan.', 'Choose which event categories to display.', 'Wählen Sie die angezeigten Terminkategorien.']), s('.ac2-span, .ac2-upcoming', ['Lihat kegiatan', 'View events', 'Termine ansehen'], ['Buka kegiatan untuk melihat rincian dan tautan terkait.', 'Open an event for details and related links.', 'Öffnen Sie einen Termin für Details und Verknüpfungen.']), s('.ac2-export', ['Ekspor jadwal', 'Export schedule', 'Zeitplan exportieren'], ['Gunakan ekspor untuk membawa jadwal ke kalender Anda.', 'Export the schedule to your calendar.', 'Exportieren Sie den Zeitplan in Ihren Kalender.'])];
 if (route === '/analytics') return [s('.an-course-list', ['Analitik per kelas', 'Analytics by class', 'Analysen nach Kurs'], ['Pilih mata kuliah untuk membaca analitik kelasnya.', 'Choose a course to explore its analytics.', 'Wählen Sie einen Kurs für dessen Analysen.'], 'scan'), s('.an-open', ['Buka analitik', 'Open analytics', 'Analysen öffnen'], ['Buka halaman analitik mata kuliah dari tautan ini.', 'Open course analytics using this link.', 'Öffnen Sie Kursanalysen über diesen Link.'])];
 if (route === '/app/riset') return [s('.ra-tabs button.active', ['Bagian riset', 'Research sections', 'Forschungsbereiche'], ['Pilih bagian untuk analitik, personalisasi, atau ekspor data riset.', 'Choose a section for analytics, personalization, or research exports.', 'Wählen Sie Analysen, Personalisierung oder Forschungsexporte.']), s('.ra-toolbar, .research-export-field', ['Batasi data', 'Scope the data', 'Daten eingrenzen'], ['Periksa filter sebelum membaca atau mengekspor data.', 'Check filters before reviewing or exporting data.', 'Prüfen Sie Filter vor Analyse oder Export.']), s('.ra-counts, .ra-metric-grid', ['Baca ringkasan', 'Read the summary', 'Übersicht lesen'], ['Tinjau jumlah dan indikator data pada ringkasan ini.', 'Review counts and indicators in this summary.', 'Prüfen Sie Anzahl und Kennzahlen dieser Übersicht.'], 'scan')];
 return undefined;
}
