/**
 * Course-thumbnail generation — server-only, using Bynara's image API.
 * Generated bytes are returned for the caller to save to the course thumbnail;
 * failures fall back to the course gradient and never block course creation.
 */
import logger from '@/lib/logger.server';

type GeneratedImage = { buffer: Buffer; mime: string; filename: string } | null;
export type GeneratedThumbnail = Exclude<GeneratedImage, null>;

/** Generates an image through Bynara's image API. */
async function requestGeneratedImage(userPrompt: string): Promise<GeneratedImage> {
	const apiKey = process.env.BYNARA_API_KEY;
	if (!apiKey) {
		logger.error('Course thumbnail: BYNARA_API_KEY is not configured.');
		return null;
	}
	const controller = new AbortController();
	const timeout = setTimeout(() => controller.abort(), 90_000);
	try {
		const response = await fetch('https://api-images.bynara.id/v1/images/generations', {
			method: 'POST',
			headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
			body: JSON.stringify({ model: process.env.BYNARA_IMAGE_MODEL || 'gpt-image-2', prompt: `${SYSTEM_PROMPT}\n\n${userPrompt}`, n: 1, size: '1024x1024', response_format: 'b64_json' }),
			signal: controller.signal,
		});
		if (!response.ok) {
			await response.text().catch(() => '');
			logger.error(`Course thumbnail Bynara image request failed (HTTP ${response.status}).`);
			return null;
		}
		const payload = await response.json() as { data?: Array<{ url?: string; b64_json?: string; revised_prompt?: string }>; error?: { message?: string } };
		const item = payload.data?.[0];
		if (item?.b64_json) {
			return { buffer: Buffer.from(item.b64_json, 'base64'), mime: 'image/png', filename: 'thumbnail.png' };
		}
		if (item?.url) {
			const imageResponse = await fetch(item.url, { signal: controller.signal });
			if (!imageResponse.ok) throw new Error(`image download HTTP ${imageResponse.status}`);
			const mime = imageResponse.headers.get('content-type') || 'image/png';
			const ext = mime.includes('jpeg') ? 'jpg' : mime.includes('webp') ? 'webp' : 'png';
			const buffer = Buffer.from(await imageResponse.arrayBuffer());
			if (buffer.length) return { buffer, mime, filename: `thumbnail.${ext}` };
		}
		logger.error('Course thumbnail Bynara image response had no usable image.');
		return null;
	} catch (error) {
		logger.error(`Course thumbnail Bynara image request failed: ${error instanceof Error ? error.message : String(error)}`);
		return null;
	} finally {
		clearTimeout(timeout);
	}
}
const SYSTEM_PROMPT = `You are a course-thumbnail image generator for an Indonesian university learning platform.
When the user describes a course, generate exactly ONE thumbnail image that visually represents its subject.
Rules:
- Produce a clean, modern, abstract illustration — no readable text, no logos, no watermarks.
- Use a warm, academic, harmonious colour palette.
- The image must be suitable as a small card thumbnail (works at 400×300).
- Do not write the course title or any words inside the image.
- Always generate an image; do not reply with only text.`;

/**
 * Builds the user prompt that asks the model to generate a thumbnail for a
 * course, encoding the title (and any subject hints) so the image reflects the
 * course content.
 */
const buildUserPrompt = (title: string, code: string, description: string): string => {
	const subject = description.trim().slice(0, 400);
	const parts = [
		`Generate a thumbnail image for a university course.`,
		`Course title: "${title}".`,
	];
	if (code) parts.push(`Course code: ${code}.`);
	if (subject) parts.push(`Subject summary: ${subject}`);
	parts.push(`Create an abstract, modern illustration representing this course's subject. 4:3 aspect ratio. No text in the image.`);
	return parts.join('\n');
};

/**
 * Generates a thumbnail image for a course via Bynara and
 * resolves with the image bytes ready to save onto the `thumbnail` file field.
 * Resolves `null` on any failure — never throws — so course creation is never
 * blocked by a thumbnail problem.
 */
export async function generateCourseThumbnail(
	title: string,
	code = '',
	description = '',
): Promise<GeneratedThumbnail | null> {
	const cleanTitle = title.trim();
	if (!cleanTitle) return null;

	const prompt = buildUserPrompt(cleanTitle, code.trim(), description.trim());
	const generated = await requestGeneratedImage(prompt);
	if (!generated) {
		logger.warn('Course thumbnail: model produced no image, falling back to gradient cover.');
		return null;
	}
	return generated;
}
